"""MCP cortex tool — thin relay to cortex-api POST /dispatch.

Op registry, handlers, workflow hints, friction suggestions, and entity
completeness enrichment live in cortex-api (libs/cortex_store/dispatch_ops/).
This module is the agent-facing MCP tool surface only.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from ._agent_tools import (
    JsonArgStr,
    dispatch_arguments_error,
    parse_dispatch_arguments,
)
from ._cortex_relay import cx

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_cortex_tools(mcp: FastMCP) -> None:
    """Register the dispatch-style cortex tool on the MCP server instance."""

    @mcp.tool(title="Cortex Knowledge Graph")
    def cortex(tool: str, arguments: JsonArgStr = "{}") -> Any:
        """Cortex knowledge system — entities, assertions, relationships, edges, journals.

                tool: operation name (see table below)
                arguments: JSON-encoded object string (e.g. '{"entity_id": "type:slug"}').
                  Large/quote-heavy payloads (session_close transcript_md / handoff_prompt):
                  do NOT hand-build the JSON string — write the payload to a file and pass a
                  file-path param (transcript_jsonl_path / handoff_source_path / source_ref),
                  or use the /agent-bus CLI, which bypasses MCP shape validation.

                Operations:
                  entities          (type?, workflow_state?, limit?, query?, for_agent?)         — list entities (workflow_state filters the typed column; use todo_candidates for routine TODO retrieval). `query` is a case-insensitive literal substring filter on entity `id` and `name` (LIKE wildcards `%` and `_` are escaped); composes with `type`, `workflow_state`, and `for_agent`. `for_agent` filters to entities whose `applicable_agents` JSON-list attribute contains either `*` (universal) or the given agent slug; entities without the attribute are treated as universal.
                  entity_get        (entity_id, intent?, include_superseded?, include_edges?, edge_limit?, include_compaction_pointers?, debug?, top_k?, resolve_aliases?, raw_id?) — get entity at requested read intent. For agent orientation, prefer intent="card" (~5–10KB projection-aware read); intent="full" is large on hub entities. ``raw_id=true`` skips alias/merged_into redirect for tombstone inspection. intent="full" (default) returns EntityDetail with active assertions plus superseded_breadcrumb/superseded_corrections. intent="full-historical" returns all superseded rows with full enrichment (audit escape hatch; same payload size as pre-change default full). intent="full" with include_superseded=true is a legacy alias for full-historical (prefer the intent). intent="card" returns Card v0 (v2.4 §6.3): identity, status_summary, summary_row, top-K active assertions (default K=7), edge_type_summary, archives_to_count, section_manifest, freshness, reserved predicate_summary slot — projection-aware fetch (~5–10KB instead of full payload). intent in {"cluster","impact"} is reserved for later phases (501). Pass debug=true with intent="card" to attach fetch_plan_row_volume per §7.8.
                  entity_create     (id, type, name, description?, workflow_state?, notes?, aliases?, attributes?, source_uri?) — create entity. `id` may be the canonical compound form `type:slug` (e.g. `project:my-slug`) or a bare slug — the server canonicalizes a bare slug to `type:slug`. A mismatched type-prefix (e.g. `decision:x` with type=`project`) is rejected 422. The entity is addressable as `type:slug` via entity_get, assert, and relationship_create. Option-C traits (``confidence_band``, ``lifecycle``, ``adoption``) are NOT settable here — birth values are derived from entity type; set traits with ``entity_update`` after create (422 if passed). ``status`` is synthesized on read (Option C) — do not pass. workflow_state is the typed per-type workflow column (e.g. todo: open|in_progress|blocked|done|deferred|cancelled); auto-filled to type's initial_state when omitted and the type has a registered schema. Auditor-validatability: entities at confirmed band MUST be backed by ≥1 confidence='confirmed' assertion citing the source; session_close audit-gate flags confirmed entities with zero confirmed assertions (confirmed_entity_no_assertions) or with typed attributes unreferenced in any confirmed assertion (confirmed_attribute_no_assertion). See agent_skill:auditor-validatable-confidence.
                  entities_bulk_upsert (entities, if_exists?) — atomically create/update/skip many entities. if_exists ∈ {fail, update, skip}; default fail preserves entity_create's conflict contract. Per-item if_exists overrides the bulk default.
                  entity_update     (entity_id, name?, description?, workflow_state?, confidence_band?, lifecycle?, adoption?, notes?, aliases?, attributes?, source_uri?, resolve_aliases?, raw_id?)  — update entity. Trait write surface (``confidence_band``, ``lifecycle``, ``adoption``) — validated and persisted here only; ``status`` is not writable (synthesized on read). source_uri auto-recomputes content_hash when set. ``resolve_aliases`` (default true) and ``raw_id`` (default false) control alias/merged_into resolution on entity_id. Auditor-validatability: same audit-gate findings as entity_create apply when promoting confidence_band to 'confirmed' — back the confirmed band (and any typed attributes) with confidence='confirmed' assertions. See agent_skill:auditor-validatable-confidence.
                  entity_rekey      (old_id, new_id) — identity-preserving relabel: rewrites every child reference, seeds old_id as alias of new_id. new_id must not exist (409). Emits cortex.entity.rekeyed post-commit.
                  entity_merge      (source_id, target_id) — fold source into target (same type only, 422 cross-type). Dedup-before-repoint on partial unique indexes; source tombstoned lifecycle=merged with merged_into=target. Emits cortex.entity.merged post-commit.
                  assertion_state   (entity_id, resolve_aliases?, raw_id?) — lightweight ratification/count projection for one entity. Returns {entity_id, ratified, confirmed_count, latest_confirmed_assertion_id}. Active filter: confidence='confirmed' AND superseded_by IS NULL (no review_status filter — mirrors preflight.py::require_decision_asserted). Read-only; payload <2KB for gate-shaped callers.
                  assertion_get     (assertion_id) — read a single assertion by id (full row incl. predicate_form). Deepen target for the assertions(intent=summary) lane.
                  assertions        (entity_id?, entity_id_prefix?, filter?, seeded_by?, confidence?, review_status?, superseded?, limit?, intent?) — list assertions. `filter` is a claim substring (LIKE). `entity_id_prefix` e.g. `service:` for all service-scoped rows. `seeded_by` filters on stored provenance (post-projection family slug or passthrough pipeline id). intent="summary" (default): {id, entity_id, claim_trunc(200), confidence, review_status, derivation_type, observed_at, superseded_by, has_evidence_uris, has_enrichment} + per-row _deepen; intent="full": full enrichment rows. Deepen one row via assertion_get. compact= is boot-internal — agents use intent=summary.
                  frictions         (owner?, owner_type?, category?, seeded_by?, superseded?, limit?, intent?) — list open friction observations across friction-owning entities (service:/agent_skill:/ai_agent:), bracketed [category] claims. Default (no owner/owner_type) spans all owner types; owner_type ∈ {service, agent_skill, ai_agent} narrows; owner names one entity; service= is the back-compat alias. intent="summary" (default): compact rows + per-row _deepen; intent="full": full enrichment rows. Default limit=7. Actionable rows → codified bug ticket, the investigate→execute fix cycle: investigate (cursor: role=cursor-consult; web: role=web-consult) → dense spec + attribute distillation at investigate close; execute default = cursor-sdk generate + source_ref (attrs distilled at investigate close); cursor-implement / web-inline = fallback. Default investigate unless mechanical-only or a dense spec exists; lifecycle investigate→fix→report. `friction()` is log-only, NOT the ticket channel. See friction-review skill / consult-routing § Codified bug reports.
                  assert            (entity_id, claim, confidence, evidence, derivation_type, confidence_score?, evidence_uris?, seeded_by?, observed_at?, valid_from?, reasoning_summary?, force?, supersedes_id?, acknowledge_audit_gaps?) — write assertion. `seeded_by` write: server projects seat slug→family via `agent_seat.seat_to_family`; bare family unchanged; pipeline/unrecognized values pass through (never rejected). Response adds `seeded_by_input`, `seeded_by`, `seeded_by_projection` (`seat_to_family`|`identity`|`passthrough_unrecognized`). Menu D panel (SPLIT): assert carries claim, evidence_uris, and optional attributes=build_panel_assert_attributes(...) (assertion.attributes is SOT per consensus-steelman-posture §3.1); entity_update(attributes=...) is optional derived cache only — session-close detectors query the non-superseded assertion, not the entity blob. supersedes_id chains lineage ONLY when force=true is also set; without force the target's superseded_by is NOT updated and the new assertion is a sibling (a protocol validation_warning is returned) — prefer the `supersede` op for atomic close+create. observed_at auto-fills to now() if absent. valid_from REQUIRED when claim contains a date pattern (YYYY-MM-DD, ISO ts, named dates) unless derivation_type is an observation type. derivation_type values: inference (agent synthesis from prior context), user_statement (user told you directly), agent_observation (tool output / runtime), direct_observation (deterministic read), compression (requires chunk_id + evidence_uris — ingested document), thread_compression (requires evidence_uris — thread compaction summary; no chunk_id), quotation (requires chunk_id + evidence_uris — verbatim quote), commitment, stated, other. Full taxonomy + co-requirements returned inline in 422 body as valid_derivation_types. When confidence='confirmed', advisory validation_warnings fire for auditor-validatability gaps (no evidence_uris, derivation_type:inference, no embedded verbatim quote ≥15 chars for verbatim-expected derivation types); pass acknowledge_audit_gaps=['no_evidence_uris'|'inference_confirmed'|'no_verbatim'] to suppress individual checks with documented intent. See agent_skill:auditor-validatable-confidence. CLAIM-SHAPE (a20948): ∀ claim c: objective_observation(c) ∧ sharpens_precision(FOL,c) ⟹ default_form(c)=FOL-over-NL-anchor — record facts/measurements/structural relations/invariants/constraints in FOL/symbolic notation layered ATOP a mandatory natural-language anchor (FTS5 hybrid search + cross-tier consumers parse NL; FOL compresses STRUCTURE, ¬ substitutes for retrievability). NL_anchor(c) always; ¬(FOL replaces NL_anchor(c)). Narrative/directive bodies stay brief-pointer+sidecar (WS-B pattern), ¬ flattened into standalone FOL.
                  assertion_update  (assertion_id, superseded_by?, valid_until?, confidence?, review_status?, reviewer?, reviewed_at?, review_notes?, predicate_form?, force?) — update assertion metadata (predicate_form=NULL clears the field; other nullable fields treat absent and null identically — use supersede to retract a value). Idempotency guard: when superseded_by is being set and the target row's superseded_by is already non-null, returns 409 Conflict — pass force=true to widen the SQL CAS and overwrite a known-existing supersedence chain. See decision:cortex-api-write-serialization / assertion 9956 (WRITE_LOCK vs SQL CAS doctrine) and friction 9825.
                  supersede         (old_assertion_id, entity_id, claim, confidence, evidence, session_id, agent, evidence_uris?, derivation_type?, valid_from?, reasoning_summary?, seeded_by?, chunk_id?, confidence_score?, revision_type?, attributes?, acknowledge_audit_gaps?, force?) — atomic close+create. Optional `revision_type` ∈ {restatement, correction, status_update} stamps attributes.revision_type on the successor row (write-time edge label; default restatement when omitted; never inherited from the predecessor). Optional `attributes` merges caller metadata with revision_type on the new row. Optional `seeded_by` uses the same projection as `assert` (response metadata when explicitly provided). Unspecified optional fields are inherited from the superseded assertion (clone-then-override semantics); pass explicit null to intentionally drop a field. Idempotency guard: when the target old_assertion_id's superseded_by is already non-null, returns 409 Conflict and the new INSERT is rolled back — pass force=true to widen the SQL CAS and overwrite a known-existing supersedence chain. See decision:cortex-api-write-serialization / assertion 9956 (WRITE_LOCK vs SQL CAS doctrine) and friction 9824. When confidence='confirmed', the same advisory auditor-validatability checks as `assert` run against the post-carryover field set; pass acknowledge_audit_gaps=['no_evidence_uris'|'inference_confirmed'|'no_verbatim'] to suppress. See agent_skill:auditor-validatable-confidence.
                  relationships     (entity_id?, type_id?, limit?)          — list active relationships with names, strength
                  relationship_create (source_id, target_id, type_id, role?, strength?, evidence?, session_id?, agent?, resolve_aliases?) — create relationship with optional provenance; resolve_aliases defaults true and reports resolved_aliases when an alias is used. Valid type_id values (relationship_types registry): agent_under_poa_for, amends, assessed_on, associated_with, belongs_to, beneficiary_of, blocked_by, causes, child_of, co_occurs, co_owns, contradicts, controlled_account_of, correspondence_with, deadline_for, depends_on, depicts, elaborates, employed_by, enables, evidence_for, filed_against, filed_by, filed_in, heir_of, involves, issued_by, location_of, mentor_of, object_of, org_party_to, owns, parent_of, participant, party_to, payment_on, personal_representative_of, pertains_to, preceded_by, precedes, recipient_of, references, refused_to_provide_to, related_to, represents, requested_records_from, requires, respondent_in, responds_to, retained_by, role_in, secured_by, sibling_of, subject_of, succeeded_by, succeeds, supersedes, supplement_to, transferred_from, transferred_to, triggers, trustee_of. (`relates_to` is an EDGE type — use edge_create; the relationship analogue is `related_to`.)
                  relationships_bulk_upsert (relationships, if_exists?, resolve_aliases?) — atomically create/update/skip many relationships. if_exists ∈ {fail, update, skip}; default fail.
                  relationship_delete (relationship_id)                    — soft-delete an erroneous relationship (row preserved for provenance; no longer appears in list)
                  relationship_update (relationship_id, role?, strength?, evidence?, valid_from?, valid_until?, source_uri?, session_id?, agent?) — patch mutable fields; to fix direction or type, delete and recreate
                  stats             ()                                       — dashboard counts
                  surface_forms     (entity_id?, mention?, mention_type?, limit?) — resolution cache
                  journal_read      (limit?, agent?)                           — recent session journals; `agent` filters by seat-level operational identity
                  journal_write     (timestamp, agent, summary, domains?, decisions?, open_items?, entity_ids?, session_id?, prior_session_id?, markdown_content?) — [DEPRECATED: use session_close] write journal; auto-creates transcript entity + continues edge
                  session_close     (session_id, agent, session_summary_md, summary, transcript_depth?, {transcript_jsonl_path | transcript_md}?, domains?, decisions?, open_items?, entity_ids?, prior_session_id?, handoff_prompt? (embedded JSON/quotes → use handoff_source_path), handoff_source_path?, handoff_source_section?, expected_handoff_prompt?, expected_derived_handoff_prompt_sha256?, expected_source_file_sha256?, assistant_label?, source_ref?, source_ref_derivation?, dry_run?) — ATOMIC server-side close. Optional source_ref is canonicalized via parse_source_ref and stamped server-side on transcript.attributes.source_ref (+ source_ref_provenance) and the journal-row source_ref mirror; unparseable refs close successfully with source_ref_unparseable provenance (never 422). Advisory (not gate): source_ref present ∧ depth=none ⇒ recommend depth ≥ light. When handoff_source_path is set, derives handoff_prompt from HTML-comment marker regions (<!-- handoff:start/end --> or labeled <!-- handoff:{label}:start/end -->); stamps handoff_provenance {write_path, written_at, source_file, source_file_sha256, derivation, derived_handoff_prompt_sha256, ...} on the transcript attribute (agent-bus 1188 2-A v2). TOCTOU: expected_handoff_prompt / expected_derived_handoff_prompt_sha256 / expected_source_file_sha256 → 409 on mismatch. dry_run previews handoff_valid, derived_handoff_prompt, handoff_provenance_preview without writes. entity_get surfaces handoff_surface (verified vs unverified) for legacy source_file:null rows. transcript_depth ∈ {verbatim, light, none} (default verbatim). Depth selection: agent-skills/session-close-kernel.md (web/API/subagent); Cursor /session-end + session-close.mdc. verbatim: Cursor JSONL or web transcript_md required; server assembles dual-layer file + transcript entity. light: structural file only (session_summary_md; no transcript source required). none: journal row + continues edge only (no transcript entity/file; incompatible with handoff). transcript_jsonl_path|transcript_md required iff depth=verbatim. handoff_prompt|handoff_source_path require depth ∈ {light, verbatim}. 422/409 reasons include transcript_source.missing, handoff.requires_transcript_entity, handoff_prompt.mismatch, handoff_derived_sha256.mismatch, handoff_source_file_sha256.mismatch, session.already_closed. Response includes journal_row_id, transcript_depth; transcript_entity_id/path/content_hash null when depth=none. See agent_skill:session-close, decision:handoff-surface-consistency.
                  session_close_preflight (session_id, agent, transcript_jsonl_path, session_summary_md, summary, entity_ids?, defer_gaps?) — Validate args + path sandbox + assemble (in memory) + audit-gate health without writing. Returns {"ok": true, "turn_count": int, "byte_count": int, "audit": {...}, "warnings": [...]} on a path that would close cleanly, or {"ok": false, "error": ..., "reason": ...} otherwise. Use to surface infra/path issues before committing to a full close.
                  session_handoff_upsert (session_id, handoff_prompt, handoff_source_path?) — Upsert handoff_prompt on an already-closed session's journal row and mirror to transcript entity attributes when present. Boot omits handoffs; retrieve via entity_get(transcript:{session_id}) or journal row. 404 when session not closed; 422 when handoff_prompt empty. Idempotent upsert (replaces prior). handoff_source_path (optional, cortex-relative) stamps handoff_provenance {write_path, written_at, source_file, source_file_sha256} on the attribute so a reader can tell a file-backed handoff from a detached/bled-through string (agent-bus 1188; decision:handoff-surface-consistency). See decision:transcript-scoped-handoff-explicit-load.
                  assemble_transcript (jsonl_path, session_id, agent?, assistant_label?) — Debug/probe surface only. Returns just the verbatim layer ({"transcript_md": ..., "turn_count": int, "byte_count": int}) from a Cursor agent-transcripts JSONL. NOT used in the close path — session_close consumes the path directly and assembles server-side. Useful when inspecting what cortex-api will compose without committing to a close.
                  review_queue      (limit?)                                 — provisional entities + flagged assertions
                  edge_create       (session_id, agent, from_node, to_node, edge_type, strength?, context?) — seed reasoning connection. Common edge_types: depends_on, leads_to, caused_by, contradicts, supersedes, relates_to, evidence_for, corroborates, derived_from, extends, promises, expects, continues, analogous_to, reasoned_about. `relates_to` here is an EDGE type — the relationship analogue is `related_to`. Call edge_types for full taxonomy + directionality.
                  edges             (from_node?, to_node?, edge_type?, agent?, session_id?, limit?) — query edges
                  edge_traverse     (node, hops?, edge_type?, min_strength?) — graph traversal (1-2 hops)
                  edge_retire       (edge_id, valid_until?)                  — retire an edge
                  edge_types        ()                                        — list registered edge types
                  search            (query, limit?, superseded?, entity_type?, intent?) — FTS5 hybrid search over assertions. intent="summary" (default): compact hits {id, entity_id, truncated claim, confidence, review_status, combmax_score, retrieval_source}; intent="full": assertion-detail rows with enrichment fields (superset of summary, includes review_status). Fetch detail via entity_get(intent=card) or assertions(entity_id=...).
                  analyze_impact    (entity_id, claim, confidence?)            — semantic pre-write impact analysis (C1)
                  activate          (entity_ids, depth?, max_results?, exclude_ids?, suppress_hubs?, decay_factor?) — spreading activation
                  resolve           (uri, tag?)                                — cortex:// URI resolution
                  tag_assign        (tag_name, entity_id, assertion_id, agent) — assign/move a named tag
                  tag_list          (entity_id)                                — list tags for entity
                  tag_resolve       (tag_name, entity_id)                      — resolve tag to assertion
                  impact            (entity_id, depth?)                        — transitive impact BFS
                  resolve_assertion_chunk (assertion_id) — resolve assertion's chunk_id to RAG chunk text (URI normalization + verify-on-fetch)
                  friction          (owner, category, note, suggestion?, agent?) — log tool/schema/boot friction (observation only). `owner` accepts a bare slug (-> `service:{slug}`) or a `service:`/`agent_skill:`/`ai_agent:` entity ID; non-service owners must already exist (typo guard); `service=` is the back-compat alias. Valid categories: tool_error, tool_mismatch, tool_absent, schema_gap, boot_drift, lesson_gap, lesson_conflict, stale_context, doc_drift, protocol. To open a fix cycle (NOT friction() alone), route as the investigate→execute fix cycle: investigate (cursor: role=cursor-consult; web: role=web-consult) → dense spec + attribute distillation at investigate close; execute default = cursor-sdk generate + source_ref (attrs distilled at investigate close); cursor-implement / web-inline = fallback. Default investigate unless mechanical-only. See friction-review / consult-routing § Codified bug reports.
                  observe           (claim, entity_id?, agent?) — lightweight observation
                  rj_write          (agent, register, entry, kind?, session_id?, revises?, links?, consolidation_data?) — write reflective journal entry
                  rj_read           (entry_id)                                  — get a reflective journal entry with links
                  rj_list           (agent?, kind?, limit?, offset?)            — list reflective journal entries
                  rj_link           (entry_id, to_entry?, to_entity?, link_type?) — link entry to another entry or entity
                  rj_consolidate    (agent, register, entry, throughline, before, now, tension_points?, contradiction_set?, falsifier?, rendered_shift?, confidence?, source_entry_ids?) — write consolidation entry
                  deadlines         ()                                          — active deadlines
                  deadline_resolve  (deadline_id, resolution_note, resolved_at, evidence?, fulfilling_assertion_id?) — atomic two-write close: confirmed RESOLVED assertion + outcome:met on attributes. Eliminates ghost-deadline boot failures where agents forget the second write.
                  todo_candidates   (q/query?, limit?, workflow_state?, priority?, domain?, domain_exclude?, context?) — ranked TODO retrieval for user intent; prefer over broad open TODO enumeration
                  todo_audit        (stale_days?, limit?, domain?, priority?) — old/open TODO audit for deferral, closure, merge, or spec conversion
                  render_subgraph   (root, hops?, top_k_assertions?, include_superseded?, edge_types?) — render a cortex subgraph as deterministic markdown for session-open materialization.

        Use when:
        - Opening a session and needing a materialized canvas of a decision/todo and its related work (replaces fan-out: entity_get root + edge_traverse + entity_get per neighbor + assertions per node).
        - Building an artifact canvas for chat display.
        - Verifying a roadmap subgraph is intact after writes.

        Do NOT use for:
        - Looking up a single entity → use entity_get with intent='card'.
        - Hybrid search across cortex → use search.
        - Reasoning-edge traversal → use edge_traverse with edge_type filter (session_edges, not structural relationships).

        Hard cap: 50 entities per render. Subgraph_too_large 422 if exceeded — reduce hops or apply edge_types filter.
                  audit             (subject?, kinds?, include_filesystem?) — run gap detectors for integrity audit (graph-only default; include_filesystem=true for fs checks). Returns findings + counts. Phase 1b of cortex-graph-projection-and-audit-primitives.

                confidence values: confirmed / believed / suspected / hypothesized
                review_status values: committed / flagged / staged / rejected

                Workflow chains (successful responses carry a ``_next`` hint field):
                  entity_create → assert → relationship_create → entity_get
                  supersede → entity_get (verify old superseded, new visible)
                  session_close → capture transcript_entity_id AND content_hash from response → quote content_hash in the user-facing completion line as provenance evidence (no read-back required) → assert on relevant entities using transcript_entity_id as evidence_uri → post bus debrief
                  journal_write [DEPRECATED] → use session_close instead

                Example:
                  cortex(tool="todo_candidates", arguments='{"query": "cortex retrieval", "limit": 5}')
                  cortex(tool="assert", arguments='{"entity_id": "person:foo", "claim": "...", "confidence": "confirmed", "evidence": "..."}')
                  cortex(tool="search", arguments='{"query": "embedding \\"recall\\" tradeoffs"}')  # embedded quotes JSON-escaped; for big payloads use a file-path param
        """
        if parse_dispatch_arguments(arguments) is None:
            return dispatch_arguments_error(
                arguments, example='{"entity_id": "type:slug"}', tool="cortex"
            )
        return cx("POST", "/dispatch", {"tool": tool, "arguments": arguments})
