"""Agent-bus database layer - SQLite with WAL mode."""

from .connection import init_db
from .messages import get_messages, insert_message, list_threads, mark_read
from .threads import (
    ThreadHasReadTurns,
    consume_triage_confirm_token,
    create_thread,
    delete_thread,
    execute_triage_close,
    execute_triage_mark_read,
    get_dispatch_link_by_execution_id,
    get_thread,
    get_thread_summary,
    get_thread_turns_asc,
    get_thread_with_links,
    issue_triage_confirm_token,
    list_threads_v2,
    list_triage_candidates,
    normalize_thread_id,
    rename_thread,
    set_thread_tags,
    update_thread,
)
from .threads_atomic import (
    PendingShellContention,
    admit_dispatch,
    claim_and_post_turn,
    close_thread,
    create_thread_with_turn,
    terminate_dispatch,
)
from .turns import (
    SlugExists,
    TurnAlreadyAcknowledged,
    UnreadTurnsExist,
    bulk_mark_read_state,
    create_turn,
    delete_turn,
    get_latest_turn,
    get_latest_turn_number,
    get_thread_turn_count,
    get_turn_by_number,
    get_turns,
    get_unread_thread_toc,
    insert_turn,
    mark_turn_read,
    update_turn,
    update_turn_status,
)

__all__ = [
    "SlugExists",
    "ThreadHasReadTurns",
    "TurnAlreadyAcknowledged",
    "UnreadTurnsExist",
    "PendingShellContention",
    "admit_dispatch",
    "claim_and_post_turn",
    "close_thread",
    "consume_triage_confirm_token",
    "create_thread",
    "create_thread_with_turn",
    "bulk_mark_read_state",
    "create_turn",
    "execute_triage_close",
    "execute_triage_mark_read",
    "terminate_dispatch",
    "delete_thread",
    "delete_turn",
    "get_messages",
    "get_dispatch_link_by_execution_id",
    "get_thread",
    "get_thread_summary",
    "get_thread_turns_asc",
    "get_thread_with_links",
    "get_latest_turn",
    "get_latest_turn_number",
    "get_thread_turn_count",
    "get_turn_by_number",
    "get_turns",
    "get_unread_thread_toc",
    "init_db",
    "insert_message",
    "insert_turn",
    "issue_triage_confirm_token",
    "list_threads",
    "list_threads_v2",
    "list_triage_candidates",
    "mark_read",
    "mark_turn_read",
    "normalize_thread_id",
    "rename_thread",
    "set_thread_tags",
    "update_thread",
    "update_turn",
    "update_turn_status",
]
