"""
Event signals for Universal Stargate event-driven architecture.

All events use the UML Message structure from universal_event_bus.
Events are created via factory functions and published as Event objects.

The EventBus automatically injects:
- timestamp: ISO 8601 string with milliseconds and Z suffix
- id: Global counter for event ordering

Usage:
    from src.scheduling.events import GatewayStateChanged
    event = GatewayStateChanged(
        url="http://localhost:9998",
        connectivity="reachable",
        health="healthy",
        previous_connectivity=None,
        previous_health=None,
        transition_type="initial",
    )
    await event_bus.publish_async_nowait(event)

Domain modules:
    routing             — routing metrics, model load, token count, decision
    routing_failures    — infeasibility, eviction, upstream exclusion, divergence
    gateway             — state transitions, retries, resource updates, reservations
    model_lifecycle     — loaded/unloaded, loading, execution, capacity
    request             — request lifecycle, profile, federation snapshot
    queue               — master capacity queue
    federation_signaling — connection, telemetry, routing delegation
    federation_load     — catalog changes, VRAM drift, load orchestration
    cloud               — cloud proxy availability and catalog
    proxy               — federated request proxy layer: transformation decisions
    pipeline            — registry, embedding steps, domain verification
    system              — startup and shutdown
"""

from .cloud import (
    CLOUD_PROXY_AVAILABLE,
    CLOUD_PROXY_CATALOG_FETCH_FAILED,
    CLOUD_PROXY_CATALOG_UPDATED,
    CLOUD_PROXY_UNAVAILABLE,
    CloudProxyAvailable,
    CloudProxyCatalogFetchFailed,
    CloudProxyCatalogUpdated,
    CloudProxyUnavailable,
)
from .federation_load import (
    FEDERATION_CATALOG_VRAM_DRIFT,
    FEDERATION_GATEWAY_CATALOG_CHANGED,
    FEDERATION_LOAD_CONFIRMED,
    FEDERATION_LOAD_FAILED,
    FEDERATION_LOAD_REQUESTED,
    FEDERATION_ORCHESTRATOR_DECIDED,
    FEDERATION_ORCHESTRATOR_EVICTED,
    FederationCatalogVramDrift,
    FederationGatewayCatalogChanged,
    FederationGatewayResourceUpdateSignal,
    FederationLoadConfirmed,
    FederationLoadFailed,
    FederationLoadRequested,
    FederationModelLoaded,
    FederationModelUnloaded,
    FederationOrchestratorDecided,
    FederationOrchestratorEvicted,
)
from .federation_signaling import (
    FEDERATION_CONNECTION_AUTHENTICATED,
    FEDERATION_CONNECTION_ESTABLISHED,
    FEDERATION_CONNECTION_LOST,
    FEDERATION_ROUTING_DELEGATED,
    FEDERATION_ROUTING_REJECTED,
    FEDERATION_ROUTING_ROUTED_LOCAL,
    FEDERATION_TELEMETRY_APPLIED,
    FEDERATION_TELEMETRY_MARKED_STALE,
    FEDERATION_TELEMETRY_RECEIVED,
    FederationConnectionAuthenticated,
    FederationConnectionEstablished,
    FederationConnectionLost,
    FederationRoutingDelegated,
    FederationRoutingRejected,
    FederationRoutingRoutedLocal,
    FederationTelemetryApplied,
    FederationTelemetryMarkedStale,
    FederationTelemetryReceived,
)
from .gateway import (
    GATEWAY_RESOURCE_UPDATE,
    GATEWAY_RETRY_ATTEMPTED,
    GATEWAY_STATE_CHANGED,
    RESOURCE_RELEASED,
    RESOURCE_RESERVED,
    GatewayResourceUpdate,
    GatewayRetryAttempted,
    GatewayStateChanged,
    ResourceReleased,
    ResourceReserved,
)
from .model_lifecycle import (
    MODEL_CAPACITY_FREED,
    MODEL_EXECUTION_COMPLETED,
    MODEL_EXECUTION_FAILED,
    MODEL_EXECUTION_STARTED,
    MODEL_LOADED,
    MODEL_LOADING_FAILED,
    MODEL_LOADING_STARTED,
    MODEL_LOADING_STUCK,
    MODEL_UNLOADED,
    ModelCapacityFreed,
    ModelExecutionCompleted,
    ModelExecutionFailed,
    ModelExecutionStarted,
    ModelLoaded,
    ModelLoadingFailed,
    ModelLoadingStarted,
    ModelLoadingStuck,
    ModelUnloaded,
)
from .pipeline import (
    PIPELINE_REGISTRY_UNAVAILABLE,
    PIPELINE_STEP_DOMAIN_VERIFICATION_COMPLETED,
    PIPELINE_STEP_DOMAIN_VERIFICATION_STARTED,
    PIPELINE_STEP_EMBEDDING_COMPLETED,
    PIPELINE_STEP_EMBEDDING_FAILED,
    PIPELINE_STEP_EMBEDDING_STARTED,
    PipelineStepEmbeddingCompleted,
    PipelineStepEmbeddingFailed,
    PipelineStepEmbeddingStarted,
    pipeline_registry_unavailable,
    pipeline_step_domain_verification_completed,
    pipeline_step_domain_verification_started,
)
from .proxy import (
    FEDERATED_REQUEST_PROMPT_TRANSFORMATION_APPLIED,
    FEDERATED_REQUEST_PROMPT_TRANSFORMATION_FAILED,
    FEDERATED_REQUEST_PROMPT_TRANSFORMATION_SKIPPED,
    federated_request_prompt_transformation_applied,
    federated_request_prompt_transformation_failed,
    federated_request_prompt_transformation_skipped,
)
from .queue import (
    QUEUE_MASTER_ENTERED,
    QUEUE_MASTER_TIMEOUT,
    QUEUE_MASTER_TOCTOU,
    QUEUE_MASTER_WOKEN,
    QueueMasterEntered,
    QueueMasterTimedOut,
    QueueMasterToctou,
    QueueMasterWoken,
)
from .request import (
    FEDERATION_SNAPSHOT_SENT,
    MODEL_SELECTION_HEALTH_OBSERVATION,
    MODEL_SELECTION_RANK_COMPUTED,
    MODEL_SELECTION_SCORE_UPDATED,
    MODEL_SELECTION_SWITCH_ALLOWED,
    MODEL_SELECTION_SWITCH_SUPPRESSED,
    REQUEST_CAPACITY_TIMEOUT,
    REQUEST_COMPLETED,
    REQUEST_FAILED,
    REQUEST_INFERENCE_STARTED,
    REQUEST_PROCESSING,
    REQUEST_PROFILE_RESOLVED,
    REQUEST_QUEUED,
    REQUEST_REMOVED,
    REQUEST_TIMEOUT,
    FederationSnapshotSent,
    ModelSelectionHealthObservation,
    ModelSelectionRankComputed,
    ModelSelectionScoreUpdated,
    ModelSelectionSwitchAllowed,
    ModelSelectionSwitchSuppressed,
    RequestCapacityTimeout,
    RequestCompleted,
    RequestFailed,
    RequestInferenceStarted,
    RequestProcessing,
    RequestProfileResolved,
    RequestQueued,
    RequestRemoved,
    RequestTimeout,
)
from .routing import (
    MODEL_CAPACITY_OVERFLOW_ASSIGNED,
    MODEL_LOAD_COMPLETED,
    MODEL_LOAD_INITIATED,
    MODEL_LOAD_OVERFLOW_STARTED,
    REQUEST_ROUTED,
    ROUTING_DECISION,
    ROUTING_DECISION_FAILED,
    TOKEN_COUNT_COMPLETED,
    TOKEN_COUNTING_FAILED,
    ModelCapacityOverflowAssigned,
    ModelLoadCompleted,
    ModelLoadInitiated,
    ModelLoadOverflowStarted,
    RequestRouted,
    RoutingDecision,
    RoutingDecisionFailed,
    TokenCountCompleted,
    TokenCountingFailed,
)
from .routing_failures import (
    ROUTING_CAPACITY_DIVERGENCE,
    ROUTING_CAPACITY_PRESEEDED,
    ROUTING_EVICTION_BLOCKED_BUSY,
    ROUTING_EVICTION_INSUFFICIENT_PERMANENT,
    ROUTING_MODEL_INFEASIBLE,
    ROUTING_OVERFLOW_FAILED,
    ROUTING_OVERFLOW_TRIGGERED,
    ROUTING_RESOURCE_DATA_MISSING,
    ROUTING_UPSTREAM_ALL_EXCLUDED,
    RoutingCapacityDivergence,
    RoutingCapacityPreseeded,
    RoutingEvictionBlockedBusy,
    RoutingEvictionInsufficientPermanent,
    RoutingModelInfeasible,
    RoutingOverflowFailed,
    RoutingOverflowTriggered,
    RoutingResourceDataMissing,
    RoutingUpstreamAllExcluded,
)
from .system import (
    SYSTEM_SHUTDOWN,
    SYSTEM_STARTED,
    SystemShutdown,
    SystemStarted,
)

__all__ = [
    # ── routing ──────────────────────────────────────────────────────────────
    "REQUEST_ROUTED",
    "MODEL_LOAD_INITIATED",
    "MODEL_LOAD_COMPLETED",
    "MODEL_CAPACITY_OVERFLOW_ASSIGNED",
    "MODEL_LOAD_OVERFLOW_STARTED",
    "TOKEN_COUNT_COMPLETED",
    "TOKEN_COUNTING_FAILED",
    "ROUTING_DECISION",
    "ROUTING_DECISION_FAILED",
    "RequestRouted",
    "ModelLoadInitiated",
    "ModelLoadCompleted",
    "ModelCapacityOverflowAssigned",
    "ModelLoadOverflowStarted",
    "TokenCountCompleted",
    "TokenCountingFailed",
    "RoutingDecision",
    "RoutingDecisionFailed",
    # ── routing_failures ─────────────────────────────────────────────────────
    "ROUTING_RESOURCE_DATA_MISSING",
    "ROUTING_MODEL_INFEASIBLE",
    "ROUTING_EVICTION_BLOCKED_BUSY",
    "ROUTING_EVICTION_INSUFFICIENT_PERMANENT",
    "ROUTING_UPSTREAM_ALL_EXCLUDED",
    "ROUTING_CAPACITY_DIVERGENCE",
    "ROUTING_CAPACITY_PRESEEDED",
    "ROUTING_OVERFLOW_TRIGGERED",
    "ROUTING_OVERFLOW_FAILED",
    "RoutingResourceDataMissing",
    "RoutingModelInfeasible",
    "RoutingEvictionBlockedBusy",
    "RoutingEvictionInsufficientPermanent",
    "RoutingUpstreamAllExcluded",
    "RoutingCapacityDivergence",
    "RoutingCapacityPreseeded",
    "RoutingOverflowTriggered",
    "RoutingOverflowFailed",
    # ── gateway ──────────────────────────────────────────────────────────────
    "GATEWAY_STATE_CHANGED",
    "GATEWAY_RETRY_ATTEMPTED",
    "GATEWAY_RESOURCE_UPDATE",
    "RESOURCE_RESERVED",
    "RESOURCE_RELEASED",
    "GatewayStateChanged",
    "GatewayRetryAttempted",
    "GatewayResourceUpdate",
    "ResourceReserved",
    "ResourceReleased",
    # ── model_lifecycle ──────────────────────────────────────────────────────
    "MODEL_LOADED",
    "MODEL_UNLOADED",
    "MODEL_LOADING_STARTED",
    "MODEL_LOADING_FAILED",
    "MODEL_LOADING_STUCK",
    "MODEL_EXECUTION_STARTED",
    "MODEL_EXECUTION_COMPLETED",
    "MODEL_EXECUTION_FAILED",
    "MODEL_CAPACITY_FREED",
    "ModelLoaded",
    "ModelUnloaded",
    "ModelLoadingStarted",
    "ModelLoadingFailed",
    "ModelLoadingStuck",
    "ModelExecutionStarted",
    "ModelExecutionCompleted",
    "ModelExecutionFailed",
    "ModelCapacityFreed",
    # ── request ──────────────────────────────────────────────────────────────
    "REQUEST_QUEUED",
    "REQUEST_PROCESSING",
    "REQUEST_INFERENCE_STARTED",
    "REQUEST_PROFILE_RESOLVED",
    "REQUEST_COMPLETED",
    "REQUEST_FAILED",
    "REQUEST_TIMEOUT",
    "REQUEST_CAPACITY_TIMEOUT",
    "REQUEST_REMOVED",
    "FEDERATION_SNAPSHOT_SENT",
    "RequestQueued",
    "RequestProcessing",
    "RequestInferenceStarted",
    "RequestProfileResolved",
    "RequestCompleted",
    "RequestFailed",
    "RequestTimeout",
    "RequestCapacityTimeout",
    "RequestRemoved",
    "FederationSnapshotSent",
    # ── model selection reputation ──────────────────────────────────────────
    "MODEL_SELECTION_HEALTH_OBSERVATION",
    "MODEL_SELECTION_SCORE_UPDATED",
    "MODEL_SELECTION_RANK_COMPUTED",
    "MODEL_SELECTION_SWITCH_SUPPRESSED",
    "MODEL_SELECTION_SWITCH_ALLOWED",
    "ModelSelectionHealthObservation",
    "ModelSelectionScoreUpdated",
    "ModelSelectionRankComputed",
    "ModelSelectionSwitchSuppressed",
    "ModelSelectionSwitchAllowed",
    # ── queue ────────────────────────────────────────────────────────────────
    "QUEUE_MASTER_ENTERED",
    "QUEUE_MASTER_WOKEN",
    "QUEUE_MASTER_TIMEOUT",
    "QUEUE_MASTER_TOCTOU",
    "QueueMasterEntered",
    "QueueMasterWoken",
    "QueueMasterTimedOut",
    "QueueMasterToctou",
    # ── federation_signaling ─────────────────────────────────────────────────
    "FEDERATION_CONNECTION_ESTABLISHED",
    "FEDERATION_CONNECTION_LOST",
    "FEDERATION_CONNECTION_AUTHENTICATED",
    "FEDERATION_TELEMETRY_RECEIVED",
    "FEDERATION_TELEMETRY_MARKED_STALE",
    "FEDERATION_TELEMETRY_APPLIED",
    "FEDERATION_ROUTING_DELEGATED",
    "FEDERATION_ROUTING_ROUTED_LOCAL",
    "FEDERATION_ROUTING_REJECTED",
    "FederationConnectionEstablished",
    "FederationConnectionLost",
    "FederationConnectionAuthenticated",
    "FederationTelemetryReceived",
    "FederationTelemetryMarkedStale",
    "FederationTelemetryApplied",
    "FederationRoutingDelegated",
    "FederationRoutingRoutedLocal",
    "FederationRoutingRejected",
    # ── federation_load ──────────────────────────────────────────────────────
    "FEDERATION_GATEWAY_CATALOG_CHANGED",
    "FEDERATION_CATALOG_VRAM_DRIFT",
    "FEDERATION_LOAD_REQUESTED",
    "FEDERATION_LOAD_CONFIRMED",
    "FEDERATION_LOAD_FAILED",
    "FEDERATION_ORCHESTRATOR_DECIDED",
    "FEDERATION_ORCHESTRATOR_EVICTED",
    "FederationGatewayCatalogChanged",
    "FederationCatalogVramDrift",
    "FederationLoadRequested",
    "FederationLoadConfirmed",
    "FederationLoadFailed",
    "FederationOrchestratorDecided",
    "FederationOrchestratorEvicted",
    "FederationGatewayResourceUpdateSignal",
    "FederationModelLoaded",
    "FederationModelUnloaded",
    # ── cloud ────────────────────────────────────────────────────────────────
    "CLOUD_PROXY_AVAILABLE",
    "CLOUD_PROXY_UNAVAILABLE",
    "CLOUD_PROXY_CATALOG_UPDATED",
    "CLOUD_PROXY_CATALOG_FETCH_FAILED",
    "CloudProxyAvailable",
    "CloudProxyUnavailable",
    "CloudProxyCatalogUpdated",
    "CloudProxyCatalogFetchFailed",
    # ── proxy ────────────────────────────────────────────────────────────────
    "FEDERATED_REQUEST_PROMPT_TRANSFORMATION_APPLIED",
    "FEDERATED_REQUEST_PROMPT_TRANSFORMATION_FAILED",
    "FEDERATED_REQUEST_PROMPT_TRANSFORMATION_SKIPPED",
    "federated_request_prompt_transformation_applied",
    "federated_request_prompt_transformation_failed",
    "federated_request_prompt_transformation_skipped",
    # ── pipeline ─────────────────────────────────────────────────────────────
    "PIPELINE_REGISTRY_UNAVAILABLE",
    "PIPELINE_STEP_EMBEDDING_STARTED",
    "PIPELINE_STEP_EMBEDDING_COMPLETED",
    "PIPELINE_STEP_EMBEDDING_FAILED",
    "PIPELINE_STEP_DOMAIN_VERIFICATION_STARTED",
    "PIPELINE_STEP_DOMAIN_VERIFICATION_COMPLETED",
    "PipelineStepEmbeddingStarted",
    "PipelineStepEmbeddingCompleted",
    "PipelineStepEmbeddingFailed",
    "pipeline_registry_unavailable",
    "pipeline_step_domain_verification_started",
    "pipeline_step_domain_verification_completed",
    # ── system ───────────────────────────────────────────────────────────────
    "SYSTEM_STARTED",
    "SYSTEM_SHUTDOWN",
    "SystemStarted",
    "SystemShutdown",
]
