catalog_schema: 3
schema: llama-cpp
metadata:
  name: DeepSeek-R1-Distill-Llama-8B-Q4_K_M
  format: gguf
  arch: llama
  quant: Q4_K_M
  parameters_m: 10200
  training_context_length: 131072
  supports_chat_history: true
  input_schema: messages
download:
  huggingface:
    repo: bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF
    verified: true
    file: DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf
  size_bytes: 4920736608
  sha256: 87bcba20b4846d8dadf753d3ff48f9285d131fc95e3e0e7e934d4f20bc896f5d
