catalog_schema: 3
schema: llama-cpp
metadata:
  name: gemma-3-12b-it-Q4_K_M
  format: gguf
  arch: gemma3
  quant: Q4_K_M
  parameters_m: 14155
  training_context_length: 131072
  supports_chat_history: true
  input_schema: messages
download:
  huggingface:
    repo: unsloth/gemma-3-12b-it-GGUF
    verified: true
    file: gemma-3-12b-it-Q4_K_M.gguf
  size_bytes: 7300778336
  sha256: 15b8fd9d8672cd4240c178c217ca781409291f34e353d2e913b29c7602ceb3ff
