catalog_schema: 3
schema: llama-cpp
metadata:
  name: Qwen2.5-14B-Instruct-Q4_K_M
  format: gguf
  arch: qwen2
  quant: Q4_K_M
  parameters_m: 21894
  training_context_length: 32768
  supports_chat_history: true
  input_schema: messages
download:
  huggingface:
    repo: ThomasBaruzier/Qwen2.5-14B-Instruct-GGUF
    verified: true
    file: Qwen2.5-14B-Instruct-Q4_K_M.gguf
  size_bytes: 8988110944
  sha256: 3c2441d5d39ac541987930ddb48807d7513895bd1c305921177b24827521f352
