"""Step lifecycle bus event factories for pipeline execution observability.

Callers: DAGExecutor observability, step_model_fallback, token_management handler,
executor preparation. Covers step start/complete/fail, model resolution,
context-exceeded, skip, condition evaluation, and sub-pipeline expansion.
Signals in namespace pipeline.step.* and pipeline.subpipeline.*.
"""

from typing import Any

from universal_event_bus import Event, event_factory


@event_factory
def StepStarted(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    step_type: str,
    model_id: str | None,
    is_map_step: bool,
) -> Event:
    """
    Emitted when step execution begins (includes both regular and map steps).

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        step_type: Step type (e.g., "generate", "filter")
        model_id: Target model identifier (None if not applicable)
        is_map_step: True if step uses map execution mode
    """
    return Event(
        signal="pipeline.step.started",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "step_name": step_name,
            "step_type": step_type,
            "model_id": model_id,
            "is_map_step": is_map_step,
        },
    )


@event_factory
def StepModelResolved(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    resolved_model_id: str,
    selection_source: str,
) -> Event:
    """
    Emitted immediately after model selection, before inference begins.

    Corrects the static default carried by StepStarted with the actual model
    that will be invoked (post profile/requirements resolution).

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        resolved_model_id: Concrete model ID selected for this invocation
        selection_source: How the model was chosen (e.g. "runtime_override",
                          "intelligence_profile", "model_ref")
    """
    return Event(
        signal="pipeline.step.model.resolved",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "step_name": step_name,
            "model_id": resolved_model_id,
            "selection_source": selection_source,
        },
    )


@event_factory
def StepCompleted(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    duration_seconds: float,
    output_length: int,
    prompt_tokens: int,
    completion_tokens: int,
    model_call_count: int,
    model_id: str | None = None,
    exit_code: int | None = None,
    json_output_keys: list[str] | None = None,
    cached_tokens: int | None = None,
) -> Event:
    """Emitted when step completes successfully.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        duration_seconds: Total wall-clock duration for the step
        output_length: Raw output character length
        prompt_tokens: Prompt tokens consumed by this step
        completion_tokens: Completion tokens generated by this step
        model_call_count: Number of model calls made by this step
        model_id: Resolved model actually invoked (None for non-generate steps)
        exit_code: Optional shell_v1 exit code (present even when 0)
        json_output_keys: Optional top-level JSON output keys for observability
        cached_tokens: Provider-reported cache hits when available; omitted when
            the provider did not report the field.
    """
    payload: dict[str, Any] = {
        "pipeline_id": pipeline_id,
        "execution_id": execution_id,
        "step_name": step_name,
        "duration_seconds": duration_seconds,
        "output_length": output_length,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "model_call_count": model_call_count,
    }
    if model_id is not None:
        payload["model_id"] = model_id
    if exit_code is not None:
        payload["exit_code"] = exit_code
    if json_output_keys is not None:
        payload["json_output_keys"] = json_output_keys
    if cached_tokens is not None:
        payload["cached_tokens"] = cached_tokens
    return Event(
        signal="pipeline.step.completed",
        payload=payload,
    )


@event_factory
def StepFailed(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    duration_seconds: float | None,
    error: str,
    prompt_tokens: int = 0,
    completion_tokens: int = 0,
    model_call_count: int = 0,
    traceback: str | None = None,
) -> Event:
    """
    Emitted when step execution fails.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        duration_seconds: Time until failure (None if failed before execution)
        error: Error message
        prompt_tokens: Prompt tokens consumed before failure
        completion_tokens: Completion tokens consumed before failure
        model_call_count: Total model calls attempted before failure
        traceback: Full Python traceback (omitted when None)
    """
    payload: dict[str, Any] = {
        "pipeline_id": pipeline_id,
        "execution_id": execution_id,
        "step_name": step_name,
        "error": error,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "model_call_count": model_call_count,
    }
    if duration_seconds is not None:
        payload["duration_seconds"] = duration_seconds
    if traceback is not None:
        payload["traceback"] = traceback
    return Event(
        signal="pipeline.step.failed",
        payload=payload,
    )


@event_factory
def StepContextExceeded(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    model_id: str,
    estimated_tokens: int,
    context_length: int,
    effective_context_per_slot: int,
    prompt_chars: int,
) -> Event:
    """Emitted when estimated prompt tokens exceed the model's context window.

    Pre-flight heuristic check (chars/4).  Accompanies the recorder-only
    ContextExceeded event with a canonical bus signal for live debugging.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        model_id: Model under evaluation
        estimated_tokens: Estimated prompt token count
        context_length: Model context length
        effective_context_per_slot: Context divided by max_parallel_requests
        prompt_chars: Prompt character count used for estimation
    """
    return Event(
        signal="pipeline.step.context.exceeded",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "step_name": step_name,
            "model_id": model_id,
            "estimated_tokens": estimated_tokens,
            "context_length": context_length,
            "effective_context_per_slot": effective_context_per_slot,
            "prompt_chars": prompt_chars,
        },
    )


@event_factory
def StepSkipped(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    reason: str,
) -> Event:
    """
    Emitted when step is skipped due to condition evaluation.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        reason: Why step was skipped
    """
    return Event(
        signal="pipeline.step.skipped",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "step_name": step_name,
            "reason": reason,
        },
    )


@event_factory
def StepConditionEvaluated(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    step_name: str,
    condition: str,
    result: bool,
    available_outputs: list[str],
) -> Event:
    """Emitted when a step's condition expression is evaluated.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        step_name: Step identifier
        condition: Original condition expression
        result: Boolean evaluation result
        available_outputs: Output namespaces available at evaluation time
    """
    return Event(
        signal="pipeline.step.condition.evaluated",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "step_name": step_name,
            "condition": condition,
            "result": result,
            "available_outputs": available_outputs,
        },
    )


@event_factory
def SubPipelineExpanded(  # noqa: N802
    pipeline_id: str,
    execution_id: str,
    parent_step_name: str,
    resolved_output_step: str,
    expanded_step_count: int,
) -> Event:
    """Emitted when a ``sub_pipeline`` step is expanded into namespaced steps.

    Payload:
        pipeline_id: Pipeline identifier
        execution_id: Current execution UUID
        parent_step_name: Original sub_pipeline step name
        resolved_output_step: Namespaced output step selected as sub-pipeline output
        expanded_step_count: Number of generated namespaced steps
    """
    return Event(
        signal="pipeline.subpipeline.expanded",
        payload={
            "pipeline_id": pipeline_id,
            "execution_id": execution_id,
            "parent_step_name": parent_step_name,
            "resolved_output_step": resolved_output_step,
            "expanded_step_count": expanded_step_count,
        },
    )
