"""Federation connection, telemetry, and routing signal events.

Covers the control-plane signaling between Master and remote Edge/Relay nodes:
authentication, telemetry flow, routing delegation, VRAM probes, and gateway health.

Package-shadow of the former ``federation_signaling.py`` module. Submodules hold
implementation; this facade preserves
``from src.scheduling.events.federation_signaling import …``.
"""

# ruff: noqa: N802

from .connection import (
    FEDERATION_CONNECTION_AUTHENTICATED,
    FEDERATION_CONNECTION_ESTABLISHED,
    FEDERATION_CONNECTION_LOST,
    FEDERATION_PEER_AUTH_FAILED,
    FEDERATION_PEER_DISCONNECTED,
    FederationConnectionAuthenticated,
    FederationConnectionEstablished,
    FederationConnectionLost,
    FederationPeerAuthFailed,
    FederationPeerDisconnected,
)
from .health import (
    FEDERATION_EDGE_CONTAINER_EXITED,
    FEDERATION_GATEWAY_DEGRADED,
    FEDERATION_GATEWAY_LIVENESS_STALE,
    FEDERATION_GATEWAY_RECOVERED,
    FEDERATION_GATEWAY_UNHEALTHY,
    FEDERATION_LINK_TIMEOUT,
    FederationEdgeContainerExited,
    FederationGatewayDegraded,
    FederationGatewayLivenessStale,
    FederationGatewayRecovered,
    FederationGatewayUnhealthy,
    FederationLinkTimeout,
)
from .routing_decisions import (
    FEDERATION_ACTIVATION_FILTERED_EMPTY,
    FEDERATION_CIRCUIT_BREAKER_REQUEST_REJECTED,
    FEDERATION_REQUEST_INFERENCE_STARTED_FORWARDED,
    FEDERATION_ROUTING_DELEGATED,
    FEDERATION_ROUTING_REJECTED,
    FEDERATION_ROUTING_ROUTED_LOCAL,
    FEDERATION_VRAM_REQUEST_FAILED,
    FEDERATION_VRAM_REQUEST_SENT,
    FEDERATION_VRAM_RESPONSE_RECEIVED,
    FederationActivationFilteredEmpty,
    FederationCircuitBreakerRequestRejected,
    FederationRequestInferenceStartedForwarded,
    FederationRoutingDelegated,
    FederationRoutingRejected,
    FederationRoutingRoutedLocal,
    FederationVramRequestFailed,
    FederationVramRequestSent,
    FederationVramResponseReceived,
)
from .telemetry import (
    FEDERATED_GATEWAY_REMOVED,
    FEDERATION_MODEL_LIFECYCLE_EVENT,
    FEDERATION_RESOURCE_UPDATED,
    FEDERATION_TELEMETRY_APPLIED,
    FEDERATION_TELEMETRY_MARKED_STALE,
    FEDERATION_TELEMETRY_RECEIVED,
    FEDERATION_TELEMETRY_WIRED,
    FederatedGatewayRemoved,
    FederationModelLifecycleEvent,
    FederationResourceUpdated,
    FederationTelemetryApplied,
    FederationTelemetryMarkedStale,
    FederationTelemetryReceived,
    FederationTelemetryWired,
)

__all__ = [
    "FEDERATION_CONNECTION_ESTABLISHED",
    "FEDERATION_CONNECTION_LOST",
    "FEDERATION_CONNECTION_AUTHENTICATED",
    "FEDERATION_PEER_AUTH_FAILED",
    "FEDERATION_PEER_DISCONNECTED",
    "FEDERATION_TELEMETRY_RECEIVED",
    "FEDERATION_TELEMETRY_MARKED_STALE",
    "FEDERATION_TELEMETRY_APPLIED",
    "FEDERATION_TELEMETRY_WIRED",
    "FEDERATION_MODEL_LIFECYCLE_EVENT",
    "FEDERATION_RESOURCE_UPDATED",
    "FEDERATED_GATEWAY_REMOVED",
    "FEDERATION_ROUTING_DELEGATED",
    "FEDERATION_ROUTING_ROUTED_LOCAL",
    "FEDERATION_ROUTING_REJECTED",
    "FEDERATION_REQUEST_INFERENCE_STARTED_FORWARDED",
    "FEDERATION_VRAM_REQUEST_SENT",
    "FEDERATION_VRAM_REQUEST_FAILED",
    "FEDERATION_VRAM_RESPONSE_RECEIVED",
    "FEDERATION_ACTIVATION_FILTERED_EMPTY",
    "FEDERATION_CIRCUIT_BREAKER_REQUEST_REJECTED",
    "FEDERATION_GATEWAY_DEGRADED",
    "FEDERATION_GATEWAY_UNHEALTHY",
    "FEDERATION_GATEWAY_RECOVERED",
    "FEDERATION_GATEWAY_LIVENESS_STALE",
    "FEDERATION_EDGE_CONTAINER_EXITED",
    "FEDERATION_LINK_TIMEOUT",
    "FederationConnectionEstablished",
    "FederationConnectionLost",
    "FederationConnectionAuthenticated",
    "FederationPeerAuthFailed",
    "FederationPeerDisconnected",
    "FederationTelemetryReceived",
    "FederationTelemetryMarkedStale",
    "FederationTelemetryApplied",
    "FederationTelemetryWired",
    "FederationModelLifecycleEvent",
    "FederationResourceUpdated",
    "FederatedGatewayRemoved",
    "FederationRoutingDelegated",
    "FederationRoutingRoutedLocal",
    "FederationRoutingRejected",
    "FederationRequestInferenceStartedForwarded",
    "FederationVramRequestSent",
    "FederationVramRequestFailed",
    "FederationVramResponseReceived",
    "FederationActivationFilteredEmpty",
    "FederationCircuitBreakerRequestRejected",
    "FederationGatewayDegraded",
    "FederationGatewayUnhealthy",
    "FederationGatewayRecovered",
    "FederationGatewayLivenessStale",
    "FederationEdgeContainerExited",
    "FederationLinkTimeout",
]
