"""LLM-specific event signals and factories for Universal LLM Gateway.

Package-shadow of the former monolithic types.py. Re-exports every signal
constant and @event_factory helper so `from src.core.events.types import X`
and relative `from .types import X` keep working unchanged.
"""

from .compute_capacity import (  # noqa: F401
    COMPUTE_CAPACITY_QUEUE_ACQUIRED,
    COMPUTE_CAPACITY_QUEUE_WAIT,
    ComputeCapacityQueueAcquired,
    ComputeCapacityQueueWait,
)
from .configuration import (  # noqa: F401
    CATALOG_RELOADED,
    GATEWAY_SNAPSHOT_RESOURCE_GAP,
    CatalogReloaded,
    GatewaySnapshotResourceGap,
)
from .gateway_lifecycle import (  # noqa: F401
    GATEWAY_DRAINING,
    GATEWAY_SHUTDOWN,
    GHOST_MODEL_CLEANED,
    PHANTOM_MODEL_CLEANED,
    PHANTOM_MODEL_DETECTED,
    VRAM_ORPHAN_DETECTED,
    VRAM_STALENESS_DETECTED,
    GatewayDraining,
    GatewayShutdown,
    GhostModelCleaned,
    PhantomModelCleaned,
    PhantomModelDetected,
    VramOrphanDetected,
    VramStalenessDetected,
)
from .inference import (  # noqa: F401
    INFERENCE_COMPLETED,
    INFERENCE_FAILED,
    INFERENCE_STARTED,
    REQUEST_INFERENCE_STARTED,
    REQUEST_QUEUED,
    STREAM_CANCELLATION_COMPLETE,
    STREAM_CANCELLED,
    InferenceCompleted,
    InferenceFailed,
    InferenceStarted,
    RequestInferenceStarted,
    RequestQueued,
    StreamCancellationComplete,
    StreamCancelled,
)
from .model_lifecycle import (  # noqa: F401
    MODEL_LOAD_BLOCKED,
    MODEL_LOAD_CONTEXT_MISMATCH,
    MODEL_LOAD_FAILED,
    MODEL_LOADED,
    MODEL_LOADING_PROGRESS,
    MODEL_LOADING_STARTED,
    MODEL_UNLOADED,
    MODEL_UNLOADING_STARTED,
    ModelLoadBlocked,
    ModelLoadContextMismatch,
    ModelLoaded,
    ModelLoadFailed,
    ModelLoadingProgress,
    ModelLoadingStarted,
    ModelUnloaded,
    ModelUnloadingStarted,
)
from .system_resources import (  # noqa: F401
    INFERENCE_RESOURCE_UPDATE,
    SYSTEM_RESOURCES_UPDATED,
    InferenceResourceUpdate,
    SystemResourcesUpdated,
)
from .worker import (  # noqa: F401
    HEALTH_CHECK_FAILED,
    SOCKET_ORPHANED,
    WORKER_CRASH_DETECTED,
    WORKER_LOADING,
    HealthCheckFailed,
    SocketOrphaned,
    WorkerCrashDetected,
    WorkerLoading,
)

__all__ = [
    "CATALOG_RELOADED",
    "COMPUTE_CAPACITY_QUEUE_ACQUIRED",
    "COMPUTE_CAPACITY_QUEUE_WAIT",
    "GATEWAY_DRAINING",
    "GATEWAY_SHUTDOWN",
    "GATEWAY_SNAPSHOT_RESOURCE_GAP",
    "GHOST_MODEL_CLEANED",
    "HEALTH_CHECK_FAILED",
    "INFERENCE_COMPLETED",
    "INFERENCE_FAILED",
    "INFERENCE_RESOURCE_UPDATE",
    "INFERENCE_STARTED",
    "MODEL_LOADED",
    "MODEL_LOADING_PROGRESS",
    "MODEL_LOADING_STARTED",
    "MODEL_LOAD_BLOCKED",
    "MODEL_LOAD_CONTEXT_MISMATCH",
    "MODEL_LOAD_FAILED",
    "MODEL_UNLOADED",
    "MODEL_UNLOADING_STARTED",
    "PHANTOM_MODEL_CLEANED",
    "PHANTOM_MODEL_DETECTED",
    "REQUEST_INFERENCE_STARTED",
    "REQUEST_QUEUED",
    "SOCKET_ORPHANED",
    "STREAM_CANCELLATION_COMPLETE",
    "STREAM_CANCELLED",
    "SYSTEM_RESOURCES_UPDATED",
    "VRAM_ORPHAN_DETECTED",
    "VRAM_STALENESS_DETECTED",
    "WORKER_CRASH_DETECTED",
    "WORKER_LOADING",
    "CatalogReloaded",
    "ComputeCapacityQueueAcquired",
    "ComputeCapacityQueueWait",
    "GatewayDraining",
    "GatewayShutdown",
    "GatewaySnapshotResourceGap",
    "GhostModelCleaned",
    "HealthCheckFailed",
    "InferenceCompleted",
    "InferenceFailed",
    "InferenceResourceUpdate",
    "InferenceStarted",
    "ModelLoadBlocked",
    "ModelLoadContextMismatch",
    "ModelLoadFailed",
    "ModelLoaded",
    "ModelLoadingProgress",
    "ModelLoadingStarted",
    "ModelUnloaded",
    "ModelUnloadingStarted",
    "PhantomModelCleaned",
    "PhantomModelDetected",
    "RequestInferenceStarted",
    "RequestQueued",
    "SocketOrphaned",
    "StreamCancellationComplete",
    "StreamCancelled",
    "SystemResourcesUpdated",
    "VramOrphanDetected",
    "VramStalenessDetected",
    "WorkerCrashDetected",
    "WorkerLoading",
]
