"""Service configuration — env files, config generation, bind mount setup."""

import logging
import os
import secrets
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]
GATEWAY_DIR = Path.home() / ".gateway"
NODES_DIR = GATEWAY_DIR / "nodes"

_STARGATE_CONFIG_TEMPLATE = """\
# TUI-managed Stargate configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# Architecture:
#   Client → Master Stargate:9999 (host) → Unix socket → Edge+Gateway (container)
#   Container: network_mode=none, fully network-isolated

proxy:
  port: 9999
  host: "0.0.0.0"
  cors_enabled: true

federation:
  mode: master
  stargate_id: "master-localhost"

  local_edge:
    socket_path: "/tmp/universal-protocol/edge-localhost.sock"
    stargate_id: "edge-localhost"
    api_key: "onboarding-dev-key"

  ping_interval_ms: 15000

  # remotes: []

logging:
  level: "INFO"
  enable_console: true
  enable_file: true
  log_dir: "/tmp/logs/universal-stargate"

model_routing:
  default_sticky: true

request_queue:
  max_size: 1000
  default_timeout: 300

pipelines:
  search_paths:
    - "pipelines"
    - "pipelines.local"
    - "~/.pipelines"
  hot_reload:
    enabled: true
    debounce_ms: 2000

debug_events:
  persistence:
    enabled: false
    directory: "/tmp/stargate-events"
    max_file_size_mb: 50
    max_files: 1
    flush_interval_seconds: 1.0

# Cloud proxy integration (optional).
# Requires the cloud proxy service to be running (start via ./manage).
# cloud_proxy:
#   url: "unix:///tmp/universal-protocol/cloud-proxy.sock"

# RAG transport (optional). Default: Unix socket at /tmp/universal-protocol/rag.sock.
# Uncomment both host and port to use TCP instead (logs network exposure warning).
# rag:
#   host: "127.0.0.1"
#   port: 8100
"""

# Fallback content when service config files are unavailable
_GATEWAY_SEED_FALLBACK: dict[str, str] = {
    "profiles.yaml": "profiles: {}\n",
    "model_transformations.yaml": "transformations: {}\n",
}

# ∀ file ∈ _GATEWAY_SEED_FALLBACK: if content == fallback, file was never populated
_SERVICE_CONFIG_DIR = WORKSPACE_ROOT / "services/universal-stargate/config"


def _gateway_seed_content(name: str) -> str:
    """Return seed content for a ~/.gateway config file.

    Reads from services/universal-stargate/config/ when available so that
    profiles and transformations ship with working defaults. Falls back to
    the empty-placeholder string if the source file is missing.
    """
    source = _SERVICE_CONFIG_DIR / name
    if source.exists():
        return source.read_text()
    fallback = _GATEWAY_SEED_FALLBACK.get(name, "")
    logger.warning("Service config not found: %s — using empty fallback", source)
    return fallback


def load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env file. Shared for TUI and headless relay."""
    entries: dict[str, str] = {}
    if not path.exists():
        return entries
    try:
        lines = path.read_text().splitlines()
    except OSError as exc:
        logger.warning("Could not read env file %s: %s", path, exc)
        return entries
    for line in lines:
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            key = key.strip()
            if key:
                entries[key] = os.path.expandvars(value.strip())
    return entries


def build_service_env(
    workspace_root: Path, node_env_path: Path | None = None
) -> dict[str, str]:
    """Build env dict from os.environ + .env.local + optional node env."""
    env = dict(os.environ)
    env.update(load_env_file(workspace_root / ".env.local"))
    if node_env_path:
        env.update(load_env_file(node_env_path))
    return env


def ensure_stargate_config() -> Path:
    """Return path to ~/.gateway/stargate.yaml, generating if absent or relay.

    Regenerates the master config if the existing file is a relay config
    (left behind by ``./manage relay``). Relay configs are auto-generated
    from template, so no user edits are lost.

    Also ensures sibling files that Stargate requires at startup
    (profiles.yaml, model_transformations.yaml) exist.
    """
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(f"Failed to create gateway directory {GATEWAY_DIR}: {exc}") from exc

    config_path = GATEWAY_DIR / "stargate.yaml"
    if config_path.exists() and is_relay_config(config_path):
        logger.warning(
            "Existing %s is a relay config — regenerating master config",
            config_path,
        )
        try:
            config_path.unlink()
        except OSError as exc:
            raise RuntimeError(
                f"Failed to remove relay config {config_path}: {exc}"
            ) from exc
    if not config_path.exists():
        try:
            config_path.write_text(_STARGATE_CONFIG_TEMPLATE)
        except OSError as exc:
            raise RuntimeError(f"Failed to write stargate config {config_path}: {exc}") from exc
        logger.info("Generated stargate config: %s", config_path)

    for name, fallback in _GATEWAY_SEED_FALLBACK.items():
        _ensure_seeded_gateway_file(name=name, fallback=fallback)

    return config_path


def _ensure_seeded_gateway_file(*, name: str, fallback: str) -> None:
    """Generate or reseed a gateway sibling config file when needed."""
    path = GATEWAY_DIR / name
    try:
        existing = path.read_text() if path.exists() else None
    except OSError as exc:
        raise RuntimeError(f"Failed to read gateway config {path}: {exc}") from exc
    if existing is not None and existing != fallback:
        return
    content = _gateway_seed_content(name)
    try:
        path.write_text(content)
    except OSError as exc:
        raise RuntimeError(f"Failed to write gateway config {path}: {exc}") from exc
    action = "Reseeded" if existing == fallback else "Generated"
    logger.info("%s %s", action, path)


def ensure_node_env(workspace_root: Path, node_id: str) -> Path:
    """Return path to ~/.gateway/nodes/<node_id>.env, generating if absent.

    Seeds MODEL_PATH from .env.local (MODEL_PATH_ROOT) as a one-time
    migration for existing installs, then generates a federation key.
    """
    try:
        NODES_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(f"Failed to create node env directory {NODES_DIR}: {exc}") from exc
    node_env = NODES_DIR / f"{node_id}.env"
    if node_env.exists():
        return node_env

    base_env = load_env_file(workspace_root / ".env.local")
    model_path = base_env.get("MODEL_PATH_ROOT", str(Path.home() / ".models"))
    federation_key = secrets.token_hex(24)

    lines = [
        f"NODE_ID={node_id}",
        f"MODEL_PATH={model_path}",
        f"FEDERATION_KEY_EDGE={federation_key}",
    ]
    try:
        node_env.write_text("\n".join(lines) + "\n")
    except OSError as exc:
        raise RuntimeError(f"Failed to write node env {node_env}: {exc}") from exc
    logger.info("Generated node env: %s", node_env)
    return node_env


def ensure_bind_mount_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Pre-create bind mount source dirs so Docker doesn't create them as root.

    Docker daemon auto-creates missing bind mount sources owned by root:root.
    Creating them here (as the invoking user) prevents that.

    Returns an error message if any dir is root-owned, None on success.
    """
    dirs = [
        model_path,
        GATEWAY_DIR / "catalog",
        GATEWAY_DIR / "nodes",
        Path.home() / ".cache" / "vllm",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "logs",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "output",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    root_owned = [d for d in dirs if d.exists() and d.stat().st_uid == 0]
    if root_owned and os.getuid() != 0:
        paths = "\n  ".join(str(d) for d in root_owned)
        uid, gid = os.getuid(), os.getgid()
        return (
            f"Bind mount dirs owned by root (Docker created them):\n"
            f"  {paths}\n"
            f"Fix with:\n  sudo chown -R {uid}:{gid} {' '.join(str(d) for d in root_owned)}"
        )
    return None


def ensure_socket_dir() -> str | None:
    """Ensure /tmp/universal-protocol exists and is world-writable/traversable.

    Returns an error message if the directory cannot be made world-writable,
    None on success.  The container bind-mounts this directory and its appuser
    (a different uid than the host user) writes a Unix socket into it — so the
    directory must be world-writable, not just writable by the current host user.

    If the directory is root-owned (e.g. Docker daemon created it via bind-mount
    auto-creation after a host reboot), attempts recovery by removing and
    recreating it as the current user.
    """
    import stat as stat_mod

    socket_dir = Path("/tmp/universal-protocol")
    socket_dir.mkdir(parents=True, exist_ok=True)
    try:
        socket_dir.chmod(0o777)
    except PermissionError:
        owner_uid = socket_dir.stat().st_uid
        if owner_uid == 0 and os.getuid() != 0:
            logger.warning(
                "Socket dir %s is root-owned (Docker bind-mount race); "
                "attempting recovery",
                socket_dir,
            )
            recovered = _recover_root_owned_socket_dir(socket_dir)
            if not recovered:
                mode = stat_mod.S_IMODE(socket_dir.stat().st_mode)
                return (
                    f"Socket directory {socket_dir} is root-owned "
                    f"(uid={owner_uid}, mode={oct(mode)}) and recovery failed. "
                    f"Fix with: sudo rm -rf {socket_dir}"
                )
            return None
        logger.warning(
            "Cannot chmod %s (uid=%d)",
            socket_dir,
            socket_dir.stat().st_uid,
        )
    try:
        stat_result = socket_dir.stat()
    except OSError as exc:
        return f"Socket directory {socket_dir} is not accessible: {exc}"
    mode = stat_mod.S_IMODE(stat_result.st_mode)
    world_writable = bool(mode & stat_mod.S_IWOTH)
    world_executable = bool(mode & stat_mod.S_IXOTH)
    if not (world_writable and world_executable):
        return (
            f"Socket directory {socket_dir} is not writable/traversable "
            f"(owned by uid={stat_result.st_uid}, mode={oct(mode)}). "
            f"Fix with: sudo chmod 777 {socket_dir}"
        )
    return None


def _recover_root_owned_socket_dir(socket_dir: Path) -> bool:
    """Remove a root-owned socket dir and recreate as current user.

    Docker daemon creates bind-mount source dirs as root when the host path
    doesn't exist (e.g. after reboot clears tmpfs /tmp). This function
    recovers by removing the root-owned directory and recreating it.

    Returns True on success, False if recovery failed.
    """
    import shutil
    import subprocess

    _stop_edge_container_for_socket_recovery()

    # Try direct removal first (won't work on sticky-bit /tmp for root-owned dirs)
    try:
        shutil.rmtree(socket_dir)
    except PermissionError:
        # Need elevated privileges — try sudo
        result = subprocess.run(
            ["sudo", "-n", "rm", "-rf", str(socket_dir)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logger.error(
                "Cannot remove root-owned %s (sudo -n failed: %s)",
                socket_dir,
                result.stderr.strip(),
            )
            return False

    # Recreate as current user
    try:
        socket_dir.mkdir(parents=True, exist_ok=True)
        socket_dir.chmod(0o777)
    except OSError as exc:
        logger.error("Failed to recreate %s after removal: %s", socket_dir, exc)
        return False

    logger.info("Recovered root-owned socket dir: %s", socket_dir)
    return True


def _stop_edge_container_for_socket_recovery() -> None:
    """Best-effort compose down to release /tmp/universal-protocol bind mount."""
    import subprocess

    compose_file = WORKSPACE_ROOT / "docker" / "compose" / "gpu-edge.yml"
    if not compose_file.exists():
        return
    result = subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            str(compose_file),
            "down",
            "--timeout",
            "10",
        ],
        cwd=str(WORKSPACE_ROOT),
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        logger.info("Stopped edge container before socket-dir recovery")
    else:
        logger.debug(
            "docker compose down during socket-dir recovery returned %d: %s",
            result.returncode,
            (result.stderr or "").strip(),
        )


def ensure_relay_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Ensure socket dir and bind-mount dirs for relay. Return error message or None."""
    err = ensure_socket_dir()
    if err:
        return err
    return ensure_bind_mount_dirs(workspace_root, node_id, model_path)


_CLOUD_PROXY_CONFIG_TEMPLATE = """\
# Cloud Proxy configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# The cloud proxy is a separate service that holds API keys and
# forwards requests to cloud providers. Stargate connects to it
# over loopback — no API keys in Stargate config.
#
# Default transport: Unix socket (no config needed).
# For TCP access, uncomment host + port and remove socket_path:
socket_path: "/tmp/universal-protocol/cloud-proxy.sock"
# host: "127.0.0.1"
# port: 8200

# providers:
#   - provider: anthropic
#     api_key_env: ANTHROPIC_API_KEY
#     base_url: https://api.anthropic.com/v1
#     max_concurrent: 20
#     refresh_interval_hours: 6
#     allow_prefixes:
#       - "anthropic/"
#
#   - provider: openai
#     api_key_env: OPENAI_API_KEY
#     base_url: https://api.openai.com/v1
#     max_concurrent: 20
#     refresh_interval_hours: 6
#     allow_prefixes:
#       - "openai/"
"""


def ensure_cloud_proxy_config() -> Path:
    """Return path to ~/.gateway/cloud-proxy.yaml, generating if absent."""
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(f"Failed to create gateway directory {GATEWAY_DIR}: {exc}") from exc
    config_path = GATEWAY_DIR / "cloud-proxy.yaml"
    if not config_path.exists():
        try:
            config_path.write_text(_CLOUD_PROXY_CONFIG_TEMPLATE)
        except OSError as exc:
            raise RuntimeError(
                f"Failed to write cloud proxy config {config_path}: {exc}"
            ) from exc
        logger.info("Generated cloud proxy config: %s", config_path)
    return config_path


CLOUD_PROXY_SOCKET_PATH_DEFAULT = "/tmp/universal-protocol/cloud-proxy.sock"


def read_cloud_proxy_socket_path(config_path: Path | None = None) -> Path:
    """Read cloud proxy socket path from cloud-proxy.yaml.

    Returns default /tmp/universal-protocol/cloud-proxy.sock when
    socket_path is absent or UDS mode is used.
    """
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    try:
        from services.universal_cloud_proxy.config import load_config
    except ImportError as exc:
        logger.warning(
            "Could not import cloud proxy config module: %s; using default socket path",
            exc,
        )
        return Path(CLOUD_PROXY_SOCKET_PATH_DEFAULT)
    try:
        cfg = load_config(path)
        if cfg.socket_path:
            return Path(cfg.socket_path)
    except Exception as exc:
        logger.warning(
            "Could not read cloud proxy socket path from %s: %s; using default",
            path,
            exc,
        )
    return Path(CLOUD_PROXY_SOCKET_PATH_DEFAULT)


def read_cloud_proxy_port(config_path: Path | None = None) -> int:
    """Read the port from cloud-proxy.yaml (TCP mode only). DEPRECATED.

    Logs WARNING. Use read_cloud_proxy_socket_path for UDS mode.
    Returns 8200 if TCP configured, else default (for backward compat).
    """
    logger.warning(
        "read_cloud_proxy_port is deprecated; cloud proxy defaults to UDS. "
        "Use read_cloud_proxy_socket_path for UDS mode."
    )
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_port = 8200
    try:
        from services.universal_cloud_proxy.config import DEFAULT_PORT, load_config

        default_port = DEFAULT_PORT
        return load_config(path).port
    except Exception:
        logger.warning("Could not read port from %s — using default 8200", path)
    return default_port


def read_cloud_proxy_host(config_path: Path | None = None) -> str:
    """Read the host from cloud-proxy.yaml (TCP mode only). DEPRECATED.

    Logs WARNING. Use read_cloud_proxy_socket_path for UDS mode.
    """
    logger.warning(
        "read_cloud_proxy_host is deprecated; cloud proxy defaults to UDS. "
        "Use read_cloud_proxy_socket_path for UDS mode."
    )
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_host = "127.0.0.1"
    try:
        from services.universal_cloud_proxy.config import DEFAULT_HOST, load_config

        default_host = DEFAULT_HOST
        return load_config(path).host
    except Exception:
        logger.warning("Could not read host from %s — using default 127.0.0.1", path)
    return default_host


RAG_SOCKET_PATH_DEFAULT = "/tmp/universal-protocol/rag.sock"


def read_rag_socket_path() -> Path:
    """Return default RAG Unix socket path."""
    return Path(RAG_SOCKET_PATH_DEFAULT)


def read_rag_tcp_config(config_path: Path | None = None) -> tuple[str, int] | None:
    """Read RAG TCP config from stargate.yaml.

    Returns (host, port) if both rag.host and rag.port are present and valid.
    Returns None if both are absent.
    Raises ValueError on partial config (only one key) or invalid port.
    Logs WARNING when valid TCP config is used (network exposure).
    """
    path = config_path or (GATEWAY_DIR / "stargate.yaml")
    if not path.exists():
        return None
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as e:
        logger.warning("Could not parse %s: %s", path, e)
        return None
    rag = data.get("rag")
    if not isinstance(rag, dict):
        return None
    host = rag.get("host")
    port_val = rag.get("port")
    host_absent = host is None or (isinstance(host, str) and not host.strip())
    port_absent = port_val is None
    if host_absent and port_absent:
        return None
    if host_absent or port_absent:
        raise ValueError(
            "RAG TCP config requires both rag.host and rag.port; "
            "partial config is invalid"
        )
    host_str = str(host).strip() if host else ""
    if not host_str:
        raise ValueError("rag.host must be non-empty")
    try:
        port_int = int(port_val)
    except (TypeError, ValueError) as e:
        raise ValueError(f"rag.port must be an integer: {e}") from e
    if not (1 <= port_int <= 65535):
        raise ValueError(f"rag.port must be 1-65535, got {port_int}")
    logger.warning(
        "RAG using TCP (rag.host=%s, rag.port=%d) — service exposed on network",
        host_str,
        port_int,
    )
    return (host_str, port_int)


def write_cloud_proxy_url_to_stargate(proxy_url: str) -> None:
    """Update cloud_proxy.url in ~/.gateway/stargate.yaml.

    Merges cloud_proxy section; preserves rest of config. Creates file if absent.
    """
    config_path = GATEWAY_DIR / "stargate.yaml"
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.error("Could not create gateway directory %s: %s", GATEWAY_DIR, exc)
        return
    data: Any = {}
    if config_path.exists():
        try:
            data = yaml.safe_load(config_path.read_text()) or {}
        except yaml.YAMLError as e:
            logger.warning(
                "Could not parse stargate.yaml for cloud_proxy update: %s", e
            )
            return
    if not isinstance(data, dict):
        return
    if "cloud_proxy" not in data:
        data["cloud_proxy"] = {}
    data["cloud_proxy"]["url"] = proxy_url.rstrip("/")
    try:
        config_path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))
    except OSError as exc:
        logger.error("Could not write cloud proxy URL to %s: %s", config_path, exc)


def is_relay_config(config_path: Path) -> bool:
    """Detect whether stargate.yaml was generated by the relay template."""
    if not config_path.exists():
        return False
    try:
        data = yaml.safe_load(config_path.read_text()) or {}
    except (OSError, yaml.YAMLError):
        return False
    if not isinstance(data, dict):
        return False
    federation = data.get("federation")
    if not isinstance(federation, dict):
        return False
    mode = federation.get("mode")
    if not isinstance(mode, str):
        return False
    return mode.strip().lower() in {"remote", "relay"}
