"""Service configuration — env files, config generation, bind mount setup."""

from __future__ import annotations

import logging
import os
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]
GATEWAY_DIR = Path.home() / ".gateway"
NODES_DIR = GATEWAY_DIR / "nodes"

_STARGATE_CONFIG_TEMPLATE = """\
# TUI-managed Stargate configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# Architecture:
#   Client → Master Stargate:9999 (host) → Unix socket → Edge+Gateway (container)
#   Container: network_mode=none, fully network-isolated

proxy:
  port: 9999
  host: "0.0.0.0"
  cors_enabled: true

federation:
  mode: master
  stargate_id: "master-localhost"

  local_edge:
    socket_path: "/tmp/universal-protocol/edge-localhost.sock"
    stargate_id: "edge-localhost"
    api_key: "onboarding-dev-key"

  ping_interval_ms: 15000

  # remotes: []

logging:
  level: "INFO"
  enable_console: true
  enable_file: true
  log_dir: "/tmp/logs/universal-stargate"

model_routing:
  default_sticky: true

request_queue:
  max_size: 1000
  default_timeout: 300

pipelines:
  search_paths:
    - "pipelines"
    - "pipelines.local"
    - "~/.pipelines"
  hot_reload:
    enabled: true
    debounce_ms: 2000

debug_events:
  persistence:
    enabled: false
    directory: "/tmp/stargate-events"
    max_file_size_mb: 50
    max_files: 1
    flush_interval_seconds: 1.0

# Cloud proxy integration (optional).
# Requires the cloud proxy service to be running (start via ./manage).
# cloud_proxy:
#   url: "unix:///tmp/universal-protocol/cloud-proxy.sock"

# RAG transport (optional). Default: Unix socket at /tmp/universal-protocol/rag.sock.
# Uncomment both host and port to use TCP instead (logs network exposure warning).
# rag:
#   host: "127.0.0.1"
#   port: 8100
"""

# Fallback content when service config files are unavailable
_GATEWAY_SEED_FALLBACK: dict[str, str] = {
    "profiles.yaml": "profiles: {}\n",
    "model_transformations.yaml": "transformations: {}\n",
}

# ∀ file ∈ _GATEWAY_SEED_FALLBACK: if content == fallback, file was never populated
_SERVICE_CONFIG_DIR = WORKSPACE_ROOT / "services/universal-stargate/config"


def _gateway_seed_content(name: str) -> str:
    """Return seed content for a ~/.gateway config file.

    Reads from services/universal-stargate/config/ when available so that
    profiles and transformations ship with working defaults. Falls back to
    the empty-placeholder string if the source file is missing.
    """
    source = _SERVICE_CONFIG_DIR / name
    if source.exists():
        return source.read_text()
    fallback = _GATEWAY_SEED_FALLBACK.get(name, "")
    logger.warning("Service config not found: %s — using empty fallback", source)
    return fallback


def load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env file. Shared for TUI and headless relay."""
    entries: dict[str, str] = {}
    if not path.exists():
        return entries
    try:
        lines = path.read_text().splitlines()
    except OSError as exc:
        logger.warning("Could not read env file %s: %s", path, exc)
        return entries
    for line in lines:
        line = line.strip()
        if line.startswith("export "):
            line = line[len("export ") :]
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            key = key.strip()
            if key:
                entries[key] = os.path.expandvars(value.strip())
    return entries


def build_service_env(
    workspace_root: Path, node_env_path: Path | None = None
) -> dict[str, str]:
    """Build env dict from os.environ + .env.local + secrets.env + optional node env.

    Also backfills ``MCP_PUBLIC_URL`` and ``MCP_AUTH_TOKEN`` from
    ``~/.gateway/mcp.yaml`` when missing — required by the gateway/Stargate
    container for the frontier-dispatch ``remote_mcp`` code path
    (``libs/llm_adapters/_mcp_entry.resolve_mcp_env``). Both env vars must be
    set in the ``manage`` process environment for the compose passthrough in
    ``docker/compose/unix-socket.yml`` to populate the container.
    """
    env = dict(os.environ)
    env.update(load_env_file(workspace_root / ".env.local"))
    env.update(load_env_file(GATEWAY_DIR / "secrets.env"))
    # CURSOR_API_KEY_OTHER_MODELS — secondary Cursor API key for Other Models pool
    # dispatches via git-integration-worker (see cursor_sdk_context.resolve_cursor_api_key).
    if node_env_path:
        env.update(load_env_file(node_env_path))
    cfg = load_mcp_config()
    if cfg is not None:
        if not env.get("MCP_AUTH_TOKEN") and cfg.auth_token:
            env["MCP_AUTH_TOKEN"] = cfg.auth_token
        if not env.get("MCP_PUBLIC_URL") and cfg.mcp_server_url:
            env["MCP_PUBLIC_URL"] = cfg.mcp_server_url
    cortex_http = load_cortex_api_config()
    # Operator-owned bind — always mirror yaml so stale shell env cannot narrow it.
    env["CORTEX_API_HTTP_HOST"] = cortex_http.http_host
    env["CORTEX_API_HTTP_PORT"] = str(cortex_http.http_port)
    return env


def apply_checkout_code_version(
    env: dict[str, str], workspace_root: Path
) -> dict[str, str]:
    """Seal ``ULG_CODE_VERSION`` from checkout HEAD for edge compose passthrough.

    The gpu-edge container has no ``git`` binary and no ``.git`` mount; without
    this seal ``resolve_code_version()`` returns the ``unknown`` sentinel.

    Docker Compose interpolates an undefined ``${ULG_CODE_VERSION}`` to the empty
    string without warning, which still satisfies presence checks in the
    container. Callers must invoke this before ``docker compose up``; an empty or
    malformed host value is replaced, and failure to read checkout HEAD raises.
    """
    from deploy_identity.code_version import is_valid_sha40, read_checkout_head

    existing = env.get("ULG_CODE_VERSION", "").strip()
    if existing and is_valid_sha40(existing):
        env["ULG_CODE_VERSION"] = existing.lower()
        return env

    env.pop("ULG_CODE_VERSION", None)
    sha = read_checkout_head(workspace_root)
    if not sha or not is_valid_sha40(sha):
        msg = (
            f"Cannot seal ULG_CODE_VERSION from checkout HEAD at {workspace_root} "
            "(git unavailable or HEAD is not a 40-hex SHA)"
        )
        logger.error(msg)
        raise RuntimeError(msg)
    env["ULG_CODE_VERSION"] = sha.lower()
    return env


_MANAGE_TUI_LOG_DIR = Path("/tmp/logs/tui")


def bootstrap_manage_process_logging_env() -> None:
    """Set LOG_DIR before any ``universal_logging`` import in the manage TUI."""
    _MANAGE_TUI_LOG_DIR.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("LOG_DIR", str(_MANAGE_TUI_LOG_DIR))
    os.environ.setdefault("SERVICE_NAME", "manage_tui")
    os.environ.setdefault("TRUNCATE_LOGS", "true")


def apply_host_service_logging_env(
    env: dict[str, str],
    *,
    log_dir: Path | str,
    log_filename: str,
) -> None:
    """Wire ``universal_logging`` file handlers to the manage launcher log dir."""
    log_path = Path(log_dir)
    log_path.mkdir(parents=True, exist_ok=True)
    service_name = Path(log_filename).stem.replace("-", "_")
    env["LOG_DIR"] = str(log_path)
    env["SERVICE_NAME"] = service_name
    env["TRUNCATE_LOGS"] = "true"


_MCP_CONFIG_PATH = GATEWAY_DIR / "mcp.yaml"
_EVENT_SERVICE_CONFIG_PATH = GATEWAY_DIR / "event-service.yaml"

_MCP_DEFAULT_TLS_CERT_DIR = "/etc/letsencrypt/live/mcp.k-1.me"
_MCP_DEFAULT_DATA_DIR = "~/mcp-data"


@dataclass(slots=True, kw_only=True)
class McpConfig:
    """Parsed ~/.gateway/mcp.yaml."""

    auth_token: str
    auth_token_env: str | None = None
    data_dir: str = _MCP_DEFAULT_DATA_DIR
    project_dir: str | None = None
    tasks_dir: str | None = None
    tls_cert_dir: str = _MCP_DEFAULT_TLS_CERT_DIR
    brave_search_api_key: str = ""
    firefox_profile_dir: str = ""
    enable_context_tools: bool = True  # expose tasks/ context tools at all
    bridge_token: str = ""
    agent_bus_token: str = ""
    anthropic_api_key: str = ""
    openai_api_key: str = ""
    xai_api_key: str = ""
    mcp_server_url: str = ""
    web_fetcher_url: str = ""
    project_ask_url: str = ""
    cdp_ask_manage_enabled: bool = True
    # ClaudeBurst bot endpoints (TCP) — bots run on a separate host, so the
    # MCP container must reach them by IP/port instead of the in-container
    # UDS fallback (which targets a socket path that does not exist on the
    # MCP host).  Mirrors the keyset exported by
    # ``scripts/sync-and-restart-mcp.sh``.
    claudeburst_host: str = ""
    claudeburst_port: str = ""
    claudeburst_perps_host: str = ""
    claudeburst_perps_port: str = ""
    claudeburst_coinbase_host: str = ""
    claudeburst_coinbase_port: str = ""
    enable_browser_tools: bool = False
    refresh_cursor_descriptors_after_rebuild: bool = False


_MCP_CONFIG_TEMPLATE = """\
# MCP server configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# The MCP server runs in a Docker container with TLS and bearer token auth.
# It is optional — remove this file to disable MCP in fleet deploys.
#
# Generate auth_token: python3 -c "import secrets; print(secrets.token_urlsafe(32))"

# Required: bearer token for the MCP server (:443)
# Prefer env indirection for single-source secret management:
# auth_token_env: MCP_AUTH_TOKEN
auth_token: ""

# Required: project root mounted as /data/project
# Can be a single workspace or a parent directory containing multiple repos.
# project_dir: /mnt/torus/projects

# Explicit tasks directory. If unset, defaults to {project_dir}/tasks.
# Set explicitly when project_dir is a multi-repo parent.
# tasks_dir: /mnt/torus/projects/universal-llm-gateway/tasks

# Host directory for persistent file storage (mounted as /data/files)
data_dir: ~/mcp-data

# Optional: enables web_search tool. Get a key at https://brave.com/search/api/
BRAVE_SEARCH_API_KEY: ""

# Optional: Firefox profile dir for browser automation tools.
# Auto-detected from profiles.ini if not set. Override only if you want
# a specific profile other than the default.
# firefox_profile_dir: ~/.mozilla/firefox/xxxxxxxx.default-release

# tasks/ context tools (todos, journal, discoveries) — exposed by default.
# Set to false to not register the tasks/ context tools at all.
# Project and tasks mounts are always read/write; writes are unconditional.
# enable_context_tools: true

# Browser automation tools (Playwright Firefox) — disabled by default.
# Enabling this also applies a narrow seccomp relaxation (unshare/clone3/setns)
# required for Firefox's internal process sandbox. See docker/compose/mcp-server-browser.override.yml.
# enable_browser_tools: false
#
# Optional (default: false): after successful MCP rebuild/start, run
# scripts/refresh-cursor-mcp-descriptors (for local Cursor users).
# Leave disabled for non-Cursor environments.
# refresh_cursor_descriptors_after_rebuild: false
"""


@dataclass(slots=True, kw_only=True)
class EventServiceConfig:
    """Parsed ~/.gateway/event-service.yaml."""

    tcp_enabled: bool = False
    tcp_host: str = "127.0.0.1"
    tcp_ingest_port: int = 7101
    tcp_query_port: int = 7102
    retention_days: int = 2
    max_sessions: int = 2


@dataclass(slots=True, kw_only=True)
class AgentBusConfig:
    """Parsed ~/.gateway/agent-bus.yaml."""

    db_path: str = "~/.agent-bus/messages.db"
    checkpoint_auto_supersede: bool = False


@dataclass(slots=True, kw_only=True)
class CortexApiConfig:
    """Parsed ~/.gateway/cortex-api.yaml — browser /control-tower HTTP bind."""

    http_host: str = "0.0.0.0"
    http_port: int = 8202


_CORTEX_API_CONFIG_PATH = GATEWAY_DIR / "cortex-api.yaml"

_CORTEX_API_CONFIG_TEMPLATE = """\
# Cortex API browser HTTP (Control Tower)
# Generated by ./manage — edit freely, will not be overwritten.
#
# Second uvicorn on TCP serves /control-tower for LAN browsers. MCP keeps UDS.
# Restrict at the network edge if exposing beyond a trusted LAN.

http:
  host: "0.0.0.0"
  port: 8202
"""


_EVENT_SERVICE_CONFIG_TEMPLATE = """\
# Event service configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# UDS transport is always active. TCP is developer-mode additive access.
# When tcp.enabled is true, the event service listens on TCP in addition to UDS.

tcp:
  enabled: false
  host: 127.0.0.1        # host-side bind address (container binds 0.0.0.0)
  ingest_port: 7101       # NDJSON ingest (same protocol as UDS)
  query_port: 7102        # HTTP query + WebSocket subscribe

retention:
  days: 2
  max_sessions: 2
"""


_AGENT_BUS_CONFIG_PATH = GATEWAY_DIR / "agent-bus.yaml"
_AGENT_BUS_CONFIG_TEMPLATE = """\
# Agent Bus configuration
# Generated by ./manage - edit freely, will not be overwritten.
#
# Host-process runtime defaults to ~/.agent-bus/messages.db.
# Override db_path if you want the TUI-managed Agent Bus to use a different file.
#
# db_path: ~/.agent-bus/messages.db
#
# Auto-derive supersedes_turn on standing-root CHECKPOINT send/reply (G2 rollout).
# checkpoint_auto_supersede: true
"""


def ensure_cortex_api_config() -> Path:
    """Generate ~/.gateway/cortex-api.yaml template if absent."""
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    if not _CORTEX_API_CONFIG_PATH.exists():
        _CORTEX_API_CONFIG_PATH.write_text(_CORTEX_API_CONFIG_TEMPLATE)
        logger.info("Generated cortex-api config: %s", _CORTEX_API_CONFIG_PATH)
    return _CORTEX_API_CONFIG_PATH


def load_cortex_api_config() -> CortexApiConfig:
    """Load ~/.gateway/cortex-api.yaml; defaults when absent or invalid."""
    default = CortexApiConfig()
    if not _CORTEX_API_CONFIG_PATH.exists():
        return default
    try:
        raw = yaml.safe_load(_CORTEX_API_CONFIG_PATH.read_text(encoding="utf-8")) or {}
    except Exception:
        logger.error(
            "Failed to parse cortex-api config: %s",
            _CORTEX_API_CONFIG_PATH,
            exc_info=True,
        )
        return default
    if not isinstance(raw, dict):
        return default
    http = raw.get("http", {})
    if not isinstance(http, dict):
        http = {}
    host = str(http.get("host", default.http_host)).strip() or default.http_host
    try:
        port = int(http.get("port", default.http_port))
    except (TypeError, ValueError):
        port = default.http_port
    return CortexApiConfig(http_host=host, http_port=port)


def cortex_api_http_bind() -> tuple[str, int]:
    """Resolve Control Tower TCP bind from ~/.gateway/cortex-api.yaml only."""
    cfg = load_cortex_api_config()
    return cfg.http_host, cfg.http_port


def ensure_event_service_config() -> Path:
    """Generate ~/.gateway/event-service.yaml template if absent."""
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    if not _EVENT_SERVICE_CONFIG_PATH.exists():
        _EVENT_SERVICE_CONFIG_PATH.write_text(_EVENT_SERVICE_CONFIG_TEMPLATE)
        logger.info("Generated event-service config: %s", _EVENT_SERVICE_CONFIG_PATH)
    return _EVENT_SERVICE_CONFIG_PATH


def load_event_service_config() -> EventServiceConfig | None:
    """Load ~/.gateway/event-service.yaml. Returns None if absent."""
    if not _EVENT_SERVICE_CONFIG_PATH.exists():
        return None
    try:
        raw = (
            yaml.safe_load(_EVENT_SERVICE_CONFIG_PATH.read_text(encoding="utf-8")) or {}
        )
    except Exception:
        logger.error(
            "Failed to parse event-service config: %s",
            _EVENT_SERVICE_CONFIG_PATH,
            exc_info=True,
        )
        return None
    if not isinstance(raw, dict):
        return None
    tcp = raw.get("tcp", {})
    if not isinstance(tcp, dict):
        tcp = {}
    retention = raw.get("retention", {})
    if not isinstance(retention, dict):
        retention = {}
    return EventServiceConfig(
        tcp_enabled=_parse_bool(tcp.get("enabled"), default=False),
        tcp_host=str(tcp.get("host", "127.0.0.1")).strip() or "127.0.0.1",
        tcp_ingest_port=int(tcp.get("ingest_port", 7101)),
        tcp_query_port=int(tcp.get("query_port", 7102)),
        retention_days=int(retention.get("days", 2)),
        max_sessions=int(retention.get("max_sessions", 2)),
    )


def ensure_agent_bus_config() -> Path:
    """Generate ~/.gateway/agent-bus.yaml template if absent."""
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    if not _AGENT_BUS_CONFIG_PATH.exists():
        _AGENT_BUS_CONFIG_PATH.write_text(_AGENT_BUS_CONFIG_TEMPLATE)
        logger.info("Generated agent-bus config: %s", _AGENT_BUS_CONFIG_PATH)
    return _AGENT_BUS_CONFIG_PATH


def load_agent_bus_config() -> AgentBusConfig:
    """Load ~/.gateway/agent-bus.yaml, falling back to the host default path."""
    default = AgentBusConfig()
    if not _AGENT_BUS_CONFIG_PATH.exists():
        return default
    try:
        raw = yaml.safe_load(_AGENT_BUS_CONFIG_PATH.read_text(encoding="utf-8")) or {}
    except Exception:
        logger.error(
            "Failed to parse agent-bus config: %s",
            _AGENT_BUS_CONFIG_PATH,
            exc_info=True,
        )
        return default
    if not isinstance(raw, dict):
        return default
    db_path = str(raw.get("db_path", default.db_path)).strip() or default.db_path
    checkpoint_auto_supersede = _parse_bool(
        raw.get("checkpoint_auto_supersede"), default=default.checkpoint_auto_supersede
    )
    return AgentBusConfig(
        db_path=db_path,
        checkpoint_auto_supersede=checkpoint_auto_supersede,
    )


def _parse_bool(value: object, *, default: bool = False) -> bool:
    """Parse a permissive bool from YAML values; fallback to *default*."""
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "yes", "on"}:
            return True
        if normalized in {"0", "false", "no", "off", ""}:
            return False
        return default
    if isinstance(value, int | float):
        return bool(value)
    return default


def _resolve_firefox_profile(configured: str) -> str:
    """Resolve the Firefox profile directory.

    If *configured* is non-empty, expand and return it directly.
    Otherwise auto-detect the default profile from profiles.ini.
    Returns an empty string if nothing can be found.
    """
    if configured.strip():
        return str(Path(configured).expanduser())

    profiles_ini = Path.home() / ".mozilla" / "firefox" / "profiles.ini"
    if not profiles_ini.exists():
        return ""

    import configparser

    cp = configparser.ConfigParser()
    try:
        cp.read(profiles_ini)
    except configparser.Error as e:
        logger.warning("Could not parse Firefox profiles.ini: %s", e)
        return ""

    # Find the section with Default=1 (the active default profile)
    base = profiles_ini.parent
    for section in cp.sections():
        if cp.get(section, "Default", fallback="") == "1":
            rel_path = cp.get(section, "Path", fallback="")
            if rel_path:
                is_relative = cp.get(section, "IsRelative", fallback="1") == "1"
                profile_path = base / rel_path if is_relative else Path(rel_path)
                if profile_path.exists():
                    logger.info("Auto-detected Firefox profile: %s", profile_path)
                    return str(profile_path)

    return ""


def ensure_mcp_config() -> Path:
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    if not _MCP_CONFIG_PATH.exists():
        _MCP_CONFIG_PATH.write_text(_MCP_CONFIG_TEMPLATE)
        logger.info("Generated MCP config template: %s", _MCP_CONFIG_PATH)
    return _MCP_CONFIG_PATH


def load_mcp_config() -> McpConfig | None:
    """Load ~/.gateway/mcp.yaml. Returns None if absent or token resolution fails."""
    if not _MCP_CONFIG_PATH.exists():
        return None
    try:
        raw = yaml.safe_load(_MCP_CONFIG_PATH.read_text(encoding="utf-8")) or {}
    except Exception:
        logger.error("Failed to parse MCP config: %s", _MCP_CONFIG_PATH, exc_info=True)
        return None
    if not isinstance(raw, dict):
        return None
    token_env_name: str | None = None
    raw_token_env = raw.get("auth_token_env")
    if raw_token_env is not None:
        if isinstance(raw_token_env, str) and raw_token_env.strip():
            token_env_name = raw_token_env.strip()
        else:
            logger.error(
                "mcp.yaml auth_token_env must be a non-empty string when set, got: %r",
                raw_token_env,
            )

    token = ""
    if token_env_name:
        token = os.environ.get(token_env_name, "").strip()
        if not token:
            logger.warning(
                "mcp.yaml auth_token_env=%s is set but env var is missing/empty; "
                "falling back to auth_token",
                token_env_name,
            )

    if not token:
        raw_token = raw.get("auth_token", "")
        if isinstance(raw_token, str):
            token = raw_token.strip()

    if not token:
        return None

    def _get_str_or_none(key: str) -> str | None:
        value = raw.get(key)
        return str(value) if value is not None else None

    def _get_stripped_str(primary_key: str, secondary_key: str = "") -> str:
        if secondary_key:
            value = raw.get(primary_key) or raw.get(secondary_key, "")
        else:
            value = raw.get(primary_key, "")
        return str(value).strip()

    project_dir = _get_str_or_none("project_dir")
    tasks_dir = _get_str_or_none("tasks_dir")

    return McpConfig(
        auth_token=token,
        auth_token_env=token_env_name,
        data_dir=_get_stripped_str("data_dir") or _MCP_DEFAULT_DATA_DIR,
        project_dir=project_dir,
        tasks_dir=tasks_dir,
        tls_cert_dir=_get_stripped_str("tls_cert_dir") or _MCP_DEFAULT_TLS_CERT_DIR,
        brave_search_api_key=_get_stripped_str(
            "BRAVE_SEARCH_API_KEY", "brave_search_api_key"
        ),
        bridge_token=_get_stripped_str("BRIDGE_TOKEN", "bridge_token"),
        agent_bus_token=_get_stripped_str("AGENT_BUS_TOKEN", "agent_bus_token"),
        anthropic_api_key=(
            _get_stripped_str("ANTHROPIC_API_KEY", "anthropic_api_key")
            or os.environ.get("ANTHROPIC_API_KEY", "").strip()
        ),
        openai_api_key=(
            _get_stripped_str("OPENAI_API_KEY", "openai_api_key")
            or os.environ.get("OPENAI_API_KEY", "").strip()
        ),
        xai_api_key=(
            _get_stripped_str("XAI_API_KEY", "xai_api_key")
            or os.environ.get("XAI_API_KEY", "").strip()
        ),
        mcp_server_url=_get_stripped_str("mcp_server_url"),
        web_fetcher_url=_get_stripped_str("WEB_FETCHER_URL", "web_fetcher_url"),
        project_ask_url=_get_stripped_str("PROJECT_ASK_URL", "project_ask_url"),
        cdp_ask_manage_enabled=_parse_bool(
            raw.get("cdp_ask_manage_enabled", True),
            default=True,
        ),
        claudeburst_host=_get_stripped_str("CLAUDEBURST_HOST"),
        claudeburst_port=_get_stripped_str("CLAUDEBURST_PORT"),
        claudeburst_perps_host=_get_stripped_str("CLAUDEBURST_PERPS_HOST"),
        claudeburst_perps_port=_get_stripped_str("CLAUDEBURST_PERPS_PORT"),
        claudeburst_coinbase_host=_get_stripped_str("CLAUDEBURST_COINBASE_HOST"),
        claudeburst_coinbase_port=_get_stripped_str("CLAUDEBURST_COINBASE_PORT"),
        firefox_profile_dir=_resolve_firefox_profile(
            _get_stripped_str("firefox_profile_dir")
        ),
        enable_context_tools=_parse_bool(
            raw.get("enable_context_tools", True),
            default=True,
        ),
        enable_browser_tools=_parse_bool(
            raw.get("enable_browser_tools", False),
            default=False,
        ),
        refresh_cursor_descriptors_after_rebuild=_parse_bool(
            raw.get("refresh_cursor_descriptors_after_rebuild", False),
            default=False,
        ),
    )


_CORTEX_DB_PATH = Path.home() / ".cortex" / "cortex.db"
_TODOS_DB_PATH = Path.home() / ".cortex" / "todos.db"
_AGENT_BUS_DATA_DIR = Path.home() / ".agent-bus"
_AGENT_BUS_DB_PATH = _AGENT_BUS_DATA_DIR / "messages.db"
_RAG_CONFIG_PATH = Path.home() / ".gateway" / "rag.yaml"
_CLOUD_PROXY_CONFIG_PATH = GATEWAY_DIR / "cloud-proxy.yaml"


def is_mcp_configured(workspace_root: Path) -> bool:  # noqa: ARG001
    """Return True iff ~/.gateway/mcp.yaml exists with a non-empty auth token value."""
    return load_mcp_config() is not None


def is_cortex_configured() -> bool:
    """Return True when Cortex storage exists, signaling explicit local Cortex setup."""
    return (
        _CORTEX_DB_PATH.parent.exists()
        or _CORTEX_DB_PATH.exists()
        or _TODOS_DB_PATH.exists()
    )


def is_agent_bus_configured() -> bool:
    """Return True when Agent Bus data directory or sqlite DB exists locally."""
    return _AGENT_BUS_DATA_DIR.exists() or _AGENT_BUS_DB_PATH.exists()


def is_email_bridge_configured() -> bool:
    """Return True when EMAIL_BRIDGE_ROOT is set to an existing directory."""
    import os

    root = os.environ.get("EMAIL_BRIDGE_ROOT", "").strip()
    return bool(root) and Path(root).expanduser().is_dir()


def is_rag_configured() -> bool:
    """Return True when ~/.gateway/rag.yaml exists, treating RAG as opt-in."""
    return _RAG_CONFIG_PATH.exists()


_CDP_ASK_DEFAULT_PORT = 8770
_LOCALHOST_ALIASES = frozenset({"localhost", "127.0.0.1", "::1"})


def parse_project_ask_url(raw: str) -> tuple[str, int, str] | None:
    """Parse ``project_ask_url`` into ``(host, port, base_url)``."""
    from urllib.parse import urlparse

    text = raw.strip()
    if not text:
        return None
    if "://" not in text:
        text = f"http://{text}"
    parsed = urlparse(text)
    host = (parsed.hostname or "").strip()
    if not host:
        return None
    port = parsed.port if parsed.port is not None else _CDP_ASK_DEFAULT_PORT
    base = f"{parsed.scheme}://{host}:{port}"
    return host, port, base.rstrip("/")


def cdp_ask_manage_state() -> str:
    """Return ``not_enabled`` | ``disabled`` | ``enabled`` for cdp-ask manage lifecycle."""
    cfg = load_mcp_config()
    if cfg is None or not cfg.project_ask_url.strip():
        return "not_enabled"
    if not cfg.cdp_ask_manage_enabled:
        return "disabled"
    return "enabled"


def is_cdp_ask_manage_enabled() -> bool:
    """True when manage owns cdp-ask lifecycle (URL set and manage flag not false)."""
    return cdp_ask_manage_state() == "enabled"


def cdp_ask_url_config() -> tuple[str, int, str] | None:
    """Parsed URL when ``project_ask_url`` is non-empty (even if manage-disabled)."""
    cfg = load_mcp_config()
    if cfg is None:
        return None
    return parse_project_ask_url(cfg.project_ask_url)


def _local_host_identities() -> set[str]:
    import socket

    identities: set[str] = set(_LOCALHOST_ALIASES)
    try:
        identities.add(socket.gethostname())
        identities.add(socket.getfqdn())
    except OSError:
        pass
    for value in identities.copy():
        if "." in value:
            identities.add(value.split(".", 1)[0])
    return {item.strip().lower() for item in identities if item.strip()}


def _this_host_node_aliases() -> set[str]:
    """NODE_ID / env-stem aliases that describe *this* machine only.

    Fleet-wide ``nodes/*.env`` and federation remotes must NOT count as local —
    otherwise master ``io`` treats URL host ``jupiter`` as local and never SSH-
    deploys (F-1 regression).
    """
    local = _local_host_identities()
    aliases: set[str] = set()
    if not NODES_DIR.exists():
        return aliases
    for node_env in NODES_DIR.glob("*.env"):
        data = load_env_file(node_env)
        stem = node_env.stem.strip().lower()
        node_id = (data.get("NODE_ID", "") or stem).strip().lower()
        if stem in local or node_id in local:
            aliases.add(stem)
            aliases.add(node_id)
    return {item for item in aliases if item}


def is_cdp_ask_local_host(url_host: str) -> bool:
    """True when manage on this host should use local uvicorn (not SSH-to-self)."""
    host = url_host.strip().lower()
    if not host:
        return False
    if host in _LOCALHOST_ALIASES:
        return True
    identities = _local_host_identities() | _this_host_node_aliases()
    return host in identities


def resolve_cdp_ask_remote_target(url_host: str) -> tuple[str, str, str] | None:
    """Resolve ``(hostname, address, ssh_user)`` for remote cdp-ask SSH control."""
    host = url_host.strip().lower()
    if not host or is_cdp_ask_local_host(host):
        return None

    config_path = GATEWAY_DIR / "stargate.yaml"
    remotes: list[dict[str, object]] = []
    if config_path.exists():
        try:
            raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:
            raw = {}
        if isinstance(raw, dict):
            federation = raw.get("federation", {})
            if isinstance(federation, dict):
                remotes_raw = federation.get("remotes") or []
                if isinstance(remotes_raw, list):
                    remotes = [r for r in remotes_raw if isinstance(r, dict)]

    for remote in remotes:
        sid = str(remote.get("stargate_id", "")).strip()
        hostname = sid.removeprefix("relay-") if sid.startswith("relay-") else sid
        url = str(remote.get("url", "")).strip()
        from urllib.parse import urlparse

        address = (urlparse(url).hostname or "").strip()
        candidates = {hostname.lower(), address.lower()}
        if host not in candidates:
            continue
        node_env = NODES_DIR / f"{hostname}.env"
        ssh_user = load_env_file(node_env).get("SSH_USER", "").strip()
        if not ssh_user:
            continue
        return hostname, address or hostname, ssh_user

    node_env = NODES_DIR / f"{host}.env"
    if node_env.exists():
        ssh_user = load_env_file(node_env).get("SSH_USER", "").strip()
        if ssh_user:
            return host, host, ssh_user
    return None


def is_cloud_proxy_configured() -> bool:
    """Return True only when cloud proxy config exists and has at least one provider."""
    if not _CLOUD_PROXY_CONFIG_PATH.exists():
        return False
    try:
        from services.universal_cloud_proxy.config import load_config

        return len(load_config(_CLOUD_PROXY_CONFIG_PATH).providers) > 0
    except Exception:
        logger.warning(
            "is_cloud_proxy_configured: failed to load %s",
            _CLOUD_PROXY_CONFIG_PATH,
            exc_info=True,
        )
        return False


_BROWSER_OVERRIDE_COMPOSE = "docker/compose/mcp-server-browser.override.yml"
_X_ACCOUNT_KEYS = ("X_API_KEY", "X_API_SECRET", "X_ACCESS_TOKEN", "X_ACCESS_SECRET")
_DEFAULT_X_ACCOUNT_ENV = Path("/mnt/torus/projects/xpharmdbot/.env")


def _parse_export_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def apply_x_account_env(
    env: dict[str, str], *, raw: dict[str, Any] | None = None
) -> None:
    """Inject @KJMXYXX OAuth credentials for the x_dm MCP tool."""
    raw = raw or {}
    for key in _X_ACCOUNT_KEYS:
        value = str(raw.get(key) or os.environ.get(key) or env.get(key) or "").strip()
        if value:
            env[key] = value
    if all(env.get(key) for key in _X_ACCOUNT_KEYS):
        return
    env_file = str(raw.get("x_account_env_file") or "").strip()
    if not env_file and _DEFAULT_X_ACCOUNT_ENV.is_file():
        env_file = str(_DEFAULT_X_ACCOUNT_ENV)
    if not env_file:
        return
    file_values = _parse_export_env_file(Path(env_file).expanduser())
    for key in _X_ACCOUNT_KEYS:
        if not env.get(key) and file_values.get(key):
            env[key] = file_values[key]


def build_mcp_env(workspace_root: Path) -> dict[str, str]:
    """Build env dict for MCP docker compose from ~/.gateway/mcp.yaml.

    Merges the base service env with MCP-specific values from the config file.
    """
    env = build_service_env(workspace_root)
    cfg = load_mcp_config()
    if cfg is None:
        return env
    env["MCP_AUTH_TOKEN"] = cfg.auth_token
    env["MCP_DATA_DIR"] = str(Path(cfg.data_dir).expanduser())
    if cfg.project_dir:
        env["MCP_PROJECT_DIR"] = cfg.project_dir
    # tasks_dir: explicit or derived from project_dir
    if cfg.tasks_dir:
        env["MCP_TASKS_DIR"] = cfg.tasks_dir
    elif cfg.project_dir:
        env["MCP_TASKS_DIR"] = f"{cfg.project_dir}/tasks"
    if cfg.brave_search_api_key:
        env["BRAVE_SEARCH_API_KEY"] = cfg.brave_search_api_key
    if cfg.bridge_token:
        env["BRIDGE_TOKEN"] = cfg.bridge_token
    if cfg.agent_bus_token:
        env["AGENT_BUS_TOKEN"] = cfg.agent_bus_token
    if cfg.anthropic_api_key:
        env["ANTHROPIC_API_KEY"] = cfg.anthropic_api_key
    if cfg.openai_api_key:
        env["OPENAI_API_KEY"] = cfg.openai_api_key
    if cfg.xai_api_key:
        env["XAI_API_KEY"] = cfg.xai_api_key
    if cfg.mcp_server_url:
        env["MCP_SERVER_URL"] = cfg.mcp_server_url
    if cfg.web_fetcher_url:
        env["WEB_FETCHER_URL"] = cfg.web_fetcher_url
    if cfg.project_ask_url:
        env["PROJECT_ASK_URL"] = cfg.project_ask_url
    # ClaudeBurst endpoints — without these the in-container claudeburst tool
    # falls back to a UDS path that does not exist on the MCP host (bots run
    # on a separate machine), producing intermittent ``bot_unreachable`` after
    # any ``manage``-driven restart.
    for attr, env_key in (
        ("claudeburst_host", "CLAUDEBURST_HOST"),
        ("claudeburst_port", "CLAUDEBURST_PORT"),
        ("claudeburst_perps_host", "CLAUDEBURST_PERPS_HOST"),
        ("claudeburst_perps_port", "CLAUDEBURST_PERPS_PORT"),
        ("claudeburst_coinbase_host", "CLAUDEBURST_COINBASE_HOST"),
        ("claudeburst_coinbase_port", "CLAUDEBURST_COINBASE_PORT"),
    ):
        value = getattr(cfg, attr)
        if value:
            env[env_key] = value
    if cfg.firefox_profile_dir:
        env["FIREFOX_PROFILE_DIR"] = cfg.firefox_profile_dir
    env["ENABLE_BROWSER_TOOLS"] = "true" if cfg.enable_browser_tools else "false"
    # Full read/write by default; mounts are rw and writes are unconditional.
    env["MCP_PROJECT_MOUNT_MODE"] = "rw"
    env["MCP_TASKS_MOUNT_MODE"] = "rw"
    env["ENABLE_CONTEXT_TOOLS"] = "true" if cfg.enable_context_tools else "false"

    raw: dict[str, Any] = {}
    if _MCP_CONFIG_PATH.exists():
        try:
            loaded = yaml.safe_load(_MCP_CONFIG_PATH.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                raw = loaded
        except Exception:
            logger.warning("Failed to parse %s for x_account env", _MCP_CONFIG_PATH)
    apply_x_account_env(env, raw=raw)
    return env


def mcp_browser_override_path(workspace_root: Path) -> Path | None:
    """Return the browser override compose path if browser tools are enabled, else None."""
    cfg = load_mcp_config()
    if cfg is None or not cfg.enable_browser_tools:
        return None
    return workspace_root / _BROWSER_OVERRIDE_COMPOSE


def ensure_stargate_config() -> Path:
    """Return path to ~/.gateway/stargate.yaml, generating if absent or relay.

    Regenerates the master config if the existing file is a relay config
    (left behind by ``./manage relay``). Relay configs are auto-generated
    from template, so no user edits are lost.

    Also ensures sibling files that Stargate requires at startup
    (profiles.yaml, model_transformations.yaml) exist.
    """
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(
            f"Failed to create gateway directory {GATEWAY_DIR}: {exc}"
        ) from exc

    config_path = GATEWAY_DIR / "stargate.yaml"
    if config_path.exists() and is_relay_config(config_path):
        logger.warning(
            "Existing %s is a relay config — regenerating master config",
            config_path,
        )
        try:
            config_path.unlink()
        except OSError as exc:
            raise RuntimeError(
                f"Failed to remove relay config {config_path}: {exc}"
            ) from exc
    if not config_path.exists():
        try:
            config_path.write_text(_STARGATE_CONFIG_TEMPLATE)
        except OSError as exc:
            raise RuntimeError(
                f"Failed to write stargate config {config_path}: {exc}"
            ) from exc
        logger.info("Generated stargate config: %s", config_path)

    for name, fallback in _GATEWAY_SEED_FALLBACK.items():
        _ensure_seeded_gateway_file(name=name, fallback=fallback)

    return config_path


def _ensure_seeded_gateway_file(*, name: str, fallback: str) -> None:
    """Generate or reseed a gateway sibling config file when needed."""
    path = GATEWAY_DIR / name
    try:
        existing = path.read_text() if path.exists() else None
    except OSError as exc:
        raise RuntimeError(f"Failed to read gateway config {path}: {exc}") from exc
    if existing is not None and existing != fallback:
        return
    content = _gateway_seed_content(name)
    try:
        path.write_text(content)
    except OSError as exc:
        raise RuntimeError(f"Failed to write gateway config {path}: {exc}") from exc
    action = "Reseeded" if existing == fallback else "Generated"
    logger.info("%s %s", action, path)


def ensure_node_env(workspace_root: Path, node_id: str) -> Path:
    """Return path to ~/.gateway/nodes/<node_id>.env, generating if absent.

    Seeds MODEL_PATH from .env.local (MODEL_PATH_ROOT) as a one-time
    migration for existing installs, then generates a federation key.
    """
    try:
        NODES_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(
            f"Failed to create node env directory {NODES_DIR}: {exc}"
        ) from exc
    node_env = NODES_DIR / f"{node_id}.env"
    if node_env.exists():
        return node_env

    base_env = load_env_file(workspace_root / ".env.local")
    model_path = base_env.get("MODEL_PATH_ROOT", str(Path.home() / ".models"))
    federation_key = secrets.token_hex(24)

    lines = [
        f"NODE_ID={node_id}",
        f"MODEL_PATH={model_path}",
        f"FEDERATION_KEY_EDGE={federation_key}",
    ]
    try:
        node_env.write_text("\n".join(lines) + "\n")
    except OSError as exc:
        raise RuntimeError(f"Failed to write node env {node_env}: {exc}") from exc
    logger.info("Generated node env: %s", node_env)
    return node_env


def ensure_bind_mount_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Pre-create bind mount source dirs so Docker doesn't create them as root.

    Docker daemon auto-creates missing bind mount sources owned by root:root.
    Creating them here (as the invoking user) prevents that.

    Returns an error message if any dir is root-owned, None on success.
    """
    runtime_dirs = [
        workspace_root / "tmp" / "gpu-nodes" / node_id / "logs",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "output",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "catalog",
    ]
    dirs = [
        model_path,
        GATEWAY_DIR / "catalog",
        GATEWAY_DIR / "nodes",
        Path.home() / ".cache" / "vllm",
        *runtime_dirs,
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    if os.getuid() != 0:
        for d in runtime_dirs:
            if d.exists() and d.stat().st_uid == 0:
                logger.warning(
                    "Runtime bind dir %s is root-owned (Docker bind-mount race); "
                    "attempting recovery",
                    d,
                )
                _recover_root_owned_bind_dir(d)
    root_owned = [d for d in dirs if d.exists() and d.stat().st_uid == 0]
    if root_owned and os.getuid() != 0:
        paths = "\n  ".join(str(d) for d in root_owned)
        uid, gid = os.getuid(), os.getgid()
        return (
            f"Bind mount dirs owned by root (Docker created them):\n"
            f"  {paths}\n"
            f"Fix with:\n  sudo chown -R {uid}:{gid} {' '.join(str(d) for d in root_owned)}"
        )
    return None


def _recover_root_owned_bind_dir(bind_dir: Path) -> bool:
    """Remove a Docker-created runtime bind dir and recreate it as the host user."""
    import shutil

    try:
        shutil.rmtree(bind_dir)
    except FileNotFoundError:
        pass
    except OSError as exc:
        logger.error("Failed to remove root-owned bind dir %s: %s", bind_dir, exc)
        return False

    try:
        bind_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.error("Failed to recreate bind dir %s: %s", bind_dir, exc)
        return False

    logger.info("Recovered root-owned bind dir: %s", bind_dir)
    return True


def ensure_socket_dir(node_id: str | None = None) -> str | None:
    """Ensure /tmp/universal-protocol exists and is world-writable/traversable.

    Returns an error message if the directory cannot be made world-writable,
    None on success.  The container bind-mounts this directory and its appuser
    (a different uid than the host user) writes a Unix socket into it — so the
    directory must be world-writable, not just writable by the current host user.

    Docker daemon often creates the bind-mount source as root:root (no sudo
    involved on host). Recovery now uses a Docker one-off container for cleanup
    (no host sudo required). Post-recovery we recheck current mode — 777 is
    sufficient even if still owned by root.
    """
    import stat as stat_mod

    socket_dir = Path("/tmp/universal-protocol")
    socket_dir.mkdir(parents=True, exist_ok=True)
    try:
        socket_dir.chmod(0o777)
    except PermissionError:
        owner_uid = socket_dir.stat().st_uid
        if owner_uid == 0 and os.getuid() != 0:
            logger.warning(
                "Socket dir %s is root-owned (Docker bind-mount race); "
                "attempting recovery (node_id=%s)",
                socket_dir,
                node_id,
            )
            recovered = _recover_root_owned_socket_dir(socket_dir, node_id=node_id)
            if not recovered:
                # Re-check after recovery attempt — 777 is what matters
                try:
                    stat_result = socket_dir.stat()
                    mode = stat_mod.S_IMODE(stat_result.st_mode)
                    if bool(mode & stat_mod.S_IWOTH) and bool(mode & stat_mod.S_IXOTH):
                        logger.info(
                            "Recovery partial success: dir is now world-writable"
                        )
                        return None
                except OSError:
                    pass
                return (
                    f"Socket directory {socket_dir} is root-owned "
                    f"(uid={owner_uid}, mode={oct(mode)}) and recovery failed. "
                    f"Fix with: sudo rm -rf {socket_dir} (or use UI Deploy)"
                )
            return None
        logger.warning(
            "Cannot chmod %s (uid=%d)",
            socket_dir,
            socket_dir.stat().st_uid,
        )
    try:
        stat_result = socket_dir.stat()
    except OSError as exc:
        return f"Socket directory {socket_dir} is not accessible: {exc}"
    mode = stat_mod.S_IMODE(stat_result.st_mode)
    world_writable = bool(mode & stat_mod.S_IWOTH)
    world_executable = bool(mode & stat_mod.S_IXOTH)
    if not (world_writable and world_executable):
        return (
            f"Socket directory {socket_dir} is not writable/traversable "
            f"(owned by uid={stat_result.st_uid}, mode={oct(mode)}). "
            f"Fix with: sudo chmod 777 {socket_dir}"
        )
    return None


def _recover_root_owned_socket_dir(
    socket_dir: Path, node_id: str | None = None
) -> bool:
    """Remove a root-owned socket dir and recreate with correct perms.

    Docker daemon creates bind-mount target dirs as root (classic /tmp race
    after reboot or first container start). We MUST clean it without relying
    on host sudo.

    Primary path is a one-off Docker container that mounts the parent and
    cleans as root from inside the container. This fulfills "no sudo required
    — the directory itself was created without sudo".

    Stops the edge container first (node-aware project name). No fallback
    to sudo.
    """
    import subprocess

    _stop_edge_container_for_socket_recovery(node_id=node_id)

    # Primary (and only) path: Docker-based cleanup — no host sudo needed.
    # The alpine container runs as root and can delete the root-owned dir.
    try:
        cleanup_cmd = [
            "docker",
            "run",
            "--rm",
            "-v",
            f"{socket_dir.parent}:/host-tmp",
            "alpine:3",
            "sh",
            "-c",
            f"rm -rf /host-tmp/{socket_dir.name} && "
            f"mkdir -p /host-tmp/{socket_dir.name} && "
            f"chmod 777 /host-tmp/{socket_dir.name} && "
            f"chown $(id -u):$(id -g) /host-tmp/{socket_dir.name} 2>/dev/null || true",
        ]
        result = subprocess.run(
            cleanup_cmd,
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
        if result.returncode == 0:
            logger.info(
                "Recovered root-owned socket dir via Docker cleanup: %s", socket_dir
            )
            # Verify
            try:
                stat = socket_dir.stat()
                logger.info(
                    "Post-recovery ownership: uid=%s mode=%s",
                    stat.st_uid,
                    oct(stat.st_mode),
                )
            except Exception:
                pass
            return True
        else:
            logger.warning(
                "Docker cleanup of %s returned %d: %s",
                socket_dir,
                result.returncode,
                (result.stderr or result.stdout or "no output").strip()[:200],
            )
    except Exception as exc:
        logger.error("Docker socket-dir cleanup failed: %s", exc)

    # Last resort: try as current user (will fail if still root-owned)
    try:
        if socket_dir.exists():
            import shutil

            shutil.rmtree(socket_dir)
        socket_dir.mkdir(parents=True, exist_ok=True)
        socket_dir.chmod(0o777)
        logger.info("Recovered socket dir (non-root path): %s", socket_dir)
        return True
    except OSError as exc:
        logger.error("Failed to create socket dir %s: %s", socket_dir, exc)
        return False


def _stop_edge_container_for_socket_recovery(node_id: str | None = None) -> None:
    """Best-effort compose down to release /tmp/universal-protocol bind mount.

    Uses correct project name for relay nodes (edge-jupiter) so the bind mount
    is properly released before we clean the socket dir.
    """
    import subprocess

    compose_file = WORKSPACE_ROOT / "docker" / "compose" / "gpu-edge.yml"
    if not compose_file.exists():
        return

    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_file),
        "down",
        "--timeout",
        "10",
    ]
    if node_id:
        cmd.extend(["-p", f"edge-{node_id}"])

    result = subprocess.run(
        cmd,
        cwd=str(WORKSPACE_ROOT),
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        project = f"edge-{node_id}" if node_id else "default"
        logger.info(
            "Stopped edge container (project=%s) before socket-dir recovery", project
        )
    else:
        logger.debug(
            "docker compose down during socket-dir recovery returned %d: %s",
            result.returncode,
            (result.stderr or "").strip(),
        )


def ensure_relay_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Ensure socket dir and bind-mount dirs for relay. Return error message or None."""
    err = ensure_socket_dir(node_id=node_id)
    if err:
        return err
    return ensure_bind_mount_dirs(workspace_root, node_id, model_path)


_CLOUD_PROXY_CONFIG_TEMPLATE = """\
# Cloud Proxy configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# The cloud proxy is a separate service that holds API keys and
# forwards requests to cloud providers. Stargate connects to it
# over loopback — no API keys in Stargate config.
#
# Default transport: Unix socket (no config needed).
# For TCP access, uncomment host + port and remove socket_path:
socket_path: "/tmp/universal-protocol/cloud-proxy.sock"
# host: "127.0.0.1"
# port: 8200

# providers:
#   - provider: anthropic
#     api_key_env: ANTHROPIC_API_KEY
#     base_url: https://api.anthropic.com/v1
#     max_concurrent: 20
#     allow_prefixes:
#       - "anthropic/"
#
#   - provider: openai
#     api_key_env: OPENAI_API_KEY
#     base_url: https://api.openai.com/v1
#     max_concurrent: 20
#     allow_prefixes:
#       - "openai/"
"""


def ensure_cloud_proxy_config() -> Path:
    """Return path to ~/.gateway/cloud-proxy.yaml, generating if absent."""
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(
            f"Failed to create gateway directory {GATEWAY_DIR}: {exc}"
        ) from exc
    config_path = GATEWAY_DIR / "cloud-proxy.yaml"
    if not config_path.exists():
        try:
            config_path.write_text(_CLOUD_PROXY_CONFIG_TEMPLATE)
        except OSError as exc:
            raise RuntimeError(
                f"Failed to write cloud proxy config {config_path}: {exc}"
            ) from exc
        logger.info("Generated cloud proxy config: %s", config_path)
    return config_path


CLOUD_PROXY_SOCKET_PATH_DEFAULT = os.environ.get(
    "CLOUD_PROXY_SOCKET_PATH", "/tmp/universal-protocol/cloud-proxy.sock"
)


def read_cloud_proxy_socket_path(config_path: Path | None = None) -> Path:
    """Read cloud proxy socket path from cloud-proxy.yaml.

    Returns default /tmp/universal-protocol/cloud-proxy.sock when
    socket_path is absent or UDS mode is used.
    """
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    try:
        from services.universal_cloud_proxy.config import load_config
    except ImportError as exc:
        logger.warning(
            "Could not import cloud proxy config module: %s; using default socket path",
            exc,
        )
        return Path(CLOUD_PROXY_SOCKET_PATH_DEFAULT)
    try:
        cfg = load_config(path)
        if cfg.socket_path:
            return Path(cfg.socket_path)
    except (yaml.YAMLError, ValueError, OSError) as exc:
        logger.warning(
            "Could not read cloud proxy socket path from %s: %s; using default",
            path,
            exc,
        )
    return Path(CLOUD_PROXY_SOCKET_PATH_DEFAULT)


def read_cloud_proxy_port(config_path: Path | None = None) -> int:
    """Deprecated TCP-only host/port accessor for cloud-proxy config.

    Cloud Proxy now defaults to Unix Domain Socket transport and this helper
    remains only for compatibility with older TCP-based configs. Prefer
    ``read_cloud_proxy_socket_path`` for new code.
    """
    logger.warning(
        "read_cloud_proxy_port is deprecated; cloud proxy defaults to UDS. "
        "Use read_cloud_proxy_socket_path for UDS mode."
    )
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_port = 8200
    try:
        from services.universal_cloud_proxy.config import DEFAULT_PORT, load_config

        default_port = DEFAULT_PORT
        return load_config(path).port
    except (yaml.YAMLError, ValueError, OSError):
        logger.warning("Could not read port from %s — using default 8200", path)
    return default_port


def read_cloud_proxy_host(config_path: Path | None = None) -> str:
    """Deprecated TCP-only host accessor for cloud-proxy config.

    Cloud Proxy now defaults to Unix Domain Socket transport and this helper
    remains only for compatibility with older TCP-based configs. Prefer
    ``read_cloud_proxy_socket_path`` for new code.
    """
    logger.warning(
        "read_cloud_proxy_host is deprecated; cloud proxy defaults to UDS. "
        "Use read_cloud_proxy_socket_path for UDS mode."
    )
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_host = "127.0.0.1"
    try:
        from services.universal_cloud_proxy.config import DEFAULT_HOST, load_config

        default_host = DEFAULT_HOST
        return load_config(path).host
    except (yaml.YAMLError, ValueError, OSError):
        logger.warning("Could not read host from %s — using default 127.0.0.1", path)
    return default_host


RAG_SOCKET_PATH_DEFAULT = os.environ.get(
    "RAG_SOCKET_PATH", "/tmp/universal-protocol/rag.sock"
)


def read_rag_socket_path() -> Path:
    """Return default RAG Unix socket path."""
    return Path(RAG_SOCKET_PATH_DEFAULT)


def read_rag_tcp_config(config_path: Path | None = None) -> tuple[str, int] | None:
    """Read RAG TCP config from stargate.yaml.

    Returns (host, port) if both rag.host and rag.port are present and valid.
    Returns None if both are absent.
    Raises ValueError on partial config (only one key) or invalid port.
    Logs WARNING when valid TCP config is used (network exposure).
    """
    path = config_path or (GATEWAY_DIR / "stargate.yaml")
    if not path.exists():
        return None
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as e:
        logger.warning("Could not parse %s: %s", path, e)
        return None
    rag = data.get("rag")
    if not isinstance(rag, dict):
        return None
    host = rag.get("host")
    port_val = rag.get("port")
    host_absent = host is None or (isinstance(host, str) and not host.strip())
    port_absent = port_val is None
    if host_absent and port_absent:
        return None
    if host_absent or port_absent:
        raise ValueError(
            "RAG TCP config requires both rag.host and rag.port; "
            "partial config is invalid"
        )
    host_str = str(host).strip() if host else ""
    if not host_str:
        raise ValueError("rag.host must be non-empty")
    try:
        port_int = int(port_val)
    except (TypeError, ValueError) as e:
        raise ValueError(f"rag.port must be an integer: {e}") from e
    if not (1 <= port_int <= 65535):
        raise ValueError(f"rag.port must be 1-65535, got {port_int}")
    logger.warning(
        "RAG using TCP (rag.host=%s, rag.port=%d) — service exposed on network",
        host_str,
        port_int,
    )
    return (host_str, port_int)


def write_cloud_proxy_url_to_stargate(proxy_url: str) -> None:
    """Update cloud_proxy.url in ~/.gateway/stargate.yaml.

    Merges cloud_proxy section; preserves rest of config. Creates file if absent.
    """
    config_path = GATEWAY_DIR / "stargate.yaml"
    try:
        GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.error("Could not create gateway directory %s: %s", GATEWAY_DIR, exc)
        return
    data: Any = {}
    if config_path.exists():
        try:
            data = yaml.safe_load(config_path.read_text()) or {}
        except yaml.YAMLError as e:
            logger.error(
                "Failed to parse stargate.yaml for cloud_proxy update. Cloud proxy URL will not be written: %s",
                e,
            )
            return
    if not isinstance(data, dict):
        logger.error(
            "stargate.yaml content is not a dictionary; cannot update cloud_proxy URL."
        )
        return
    if "cloud_proxy" not in data:
        data["cloud_proxy"] = {}
    data["cloud_proxy"]["url"] = proxy_url.rstrip("/")
    try:
        config_path.write_text(
            yaml.dump(data, default_flow_style=False, sort_keys=False)
        )
    except OSError as exc:
        logger.error("Could not write cloud proxy URL to %s: %s", config_path, exc)


def is_relay_config(config_path: Path) -> bool:
    """Detect whether stargate.yaml was generated by the relay template."""
    if not config_path.exists():
        return False
    try:
        data = yaml.safe_load(config_path.read_text()) or {}
    except (OSError, yaml.YAMLError):
        return False
    if not isinstance(data, dict):
        return False
    federation = data.get("federation")
    if not isinstance(federation, dict):
        return False
    mode = federation.get("mode")
    if not isinstance(mode, str):
        return False
    return mode.strip().lower() in {"remote", "relay"}
