"""Service controller - build, start, stop Gateway and Stargate."""

import asyncio
import logging
import os
import secrets
import signal
from collections.abc import AsyncIterator
from pathlib import Path

from ..model.build_state import BuildState, ImageInfo
from ..model.service_state import ServiceState

logger = logging.getLogger(__name__)

_PGID_KILL_TIMEOUT = 5

_GATEWAY_DIR = Path.home() / ".gateway"
_NODES_DIR = _GATEWAY_DIR / "nodes"


def load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env file. Shared for TUI and headless relay."""
    entries: dict[str, str] = {}
    if not path.exists():
        return entries
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            entries[key.strip()] = value.strip()
    return entries

_STARGATE_CONFIG_TEMPLATE = """\
# TUI-managed Stargate configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# Architecture:
#   Client → Master Stargate:9999 (host) → Unix socket → Edge+Gateway (container)
#   Container: network_mode=none, fully network-isolated

proxy:
  port: 9999
  host: "0.0.0.0"
  cors_enabled: true

federation:
  mode: master
  stargate_id: "master-localhost"

  local_edge:
    socket_path: "/tmp/universal-protocol/edge-localhost.sock"
    stargate_id: "edge-localhost"
    api_key: "onboarding-dev-key"

  ping_interval_ms: 15000

  # remotes: []

logging:
  level: "INFO"
  enable_console: true
  enable_file: true
  log_dir: "/tmp/logs/universal-stargate"

model_routing:
  default_sticky: true

request_queue:
  max_size: 1000
  default_timeout: 300

pipelines:
  search_paths:
    - "pipelines"
    - "pipelines.local"
    - "~/.pipelines"
  hot_reload:
    enabled: true
    debounce_ms: 2000
"""


_GATEWAY_SEED_FILES: dict[str, str] = {
    "profiles.yaml": "profiles: {}\n",
    "model_transformations.yaml": "transformations: {}\n",
}


class ServiceController:
    """
    Orchestrates Docker builds and service lifecycle.

    Delegates to existing shell scripts; does not reimplement their logic.
    """

    def __init__(self, workspace_root: Path) -> None:
        self._root = workspace_root
        self._build_state = BuildState()
        self._service_state = ServiceState(workspace_root)
        self._build_process: asyncio.subprocess.Process | None = None

    @property
    def service_state(self) -> ServiceState:
        return self._service_state

    def check_model_path_ownership(self) -> str | None:
        """Return warning if MODEL_PATH is root-owned, None if OK."""
        base_env = load_env_file(self._root / ".env.local")
        model_path = Path(
            base_env.get("MODEL_PATH_ROOT", str(Path.home() / ".models"))
        ).expanduser()
        if model_path.exists() and model_path.stat().st_uid == 0 and os.getuid() != 0:
            uid, gid = os.getuid(), os.getgid()
            return (
                f"{model_path} is owned by root (Docker bind mount artifact).\n"
                f"Fix: sudo chown -R {uid}:{gid} {model_path}"
            )
        return None

    @property
    def build_running(self) -> bool:
        return self._build_process is not None

    def check_image(self) -> ImageInfo:
        return self._build_state.check_image()

    async def cancel_build(self) -> str:
        """Kill the running build process group."""
        proc = self._build_process
        if proc is None or proc.returncode is not None:
            return "No build in progress."
        try:
            os.killpg(proc.pid, signal.SIGTERM)
            try:
                await asyncio.wait_for(proc.wait(), timeout=_PGID_KILL_TIMEOUT)
            except TimeoutError:
                os.killpg(proc.pid, signal.SIGKILL)
                await proc.wait()
        except (ProcessLookupError, PermissionError) as e:
            logger.warning("cancel_build: %s", e)
        return "Build cancelled."

    async def build_image(
        self,
        *,
        scope: str = "all",
        no_cache: bool = False,
        gpu_native: bool = True,
        cpu_native: bool = True,
    ) -> AsyncIterator[str]:
        """
        Build Docker GPU image via build-gpu.sh, yielding log lines.

        Yields lines from stdout/stderr as they appear.
        """
        script = self._root / "docker" / "scripts" / "build" / "build-gpu.sh"
        if not script.exists():
            yield f"ERROR: Build script not found: {script}"
            return

        args = [str(script)]
        if cpu_native:
            args.append("--cpu-native")
        if gpu_native:
            args.append("--gpu-native")
        if no_cache:
            args.append("--no-cache")
        args.append("--refresh-source")
        if scope == "llama":
            args.append("--no-vllm")

        log_path = Path("/tmp/rebuild-gpu.log")
        cmd_line = f"$ {' '.join(args)}"
        yield cmd_line
        process = await asyncio.create_subprocess_exec(
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=str(self._root),
            start_new_session=True,
        )
        self._build_process = process
        try:
            assert process.stdout is not None
            with log_path.open("w") as log_file:
                log_file.write(cmd_line + "\n")
                log_file.flush()
                async for raw_line in process.stdout:
                    line = raw_line.decode(errors="replace").rstrip()
                    log_file.write(line + "\n")
                    log_file.flush()
                    yield line
            exit_code = await process.wait()
            with log_path.open("a") as log_file:
                if exit_code == 0:
                    msg = "Build completed successfully."
                elif exit_code == -signal.SIGTERM or exit_code == -signal.SIGKILL:
                    msg = "Build cancelled."
                else:
                    msg = f"Build FAILED (exit code {exit_code})."
                log_file.write(msg + "\n")
            yield msg
        finally:
            self._build_process = None

    async def start_gateway(self, *, node_id: str = "localhost") -> str:
        """Start Edge+Gateway container via parameterized compose."""
        compose_path = self._root / "docker" / "compose" / "gpu-edge.yml"
        if not compose_path.exists():
            return f"Compose file not found: {compose_path}"

        self._ensure_socket_dir()
        node_env_path = self._ensure_node_env(node_id)
        node_env = load_env_file(node_env_path)
        model_path = Path(node_env.get("MODEL_PATH", str(Path.home() / ".models")))
        ownership_error = self._ensure_bind_mount_dirs(node_id, model_path)
        if ownership_error:
            return ownership_error
        env = self._build_env(node_env_path)
        env["COMPOSE_PROJECT_NAME"] = f"edge-{node_id}"

        result = await asyncio.create_subprocess_exec(
            "docker",
            "compose",
            "-f",
            str(compose_path),
            "up",
            "-d",
            "--force-recreate",
            env=env,
            cwd=str(self._root),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        output = await result.communicate()
        text = output[0].decode(errors="replace") if output[0] else ""
        if result.returncode == 0:
            return f"Gateway container started (edge-{node_id}).\n{text}"
        return f"Failed to start Gateway (exit {result.returncode}).\n{text}"

    async def stop_gateway(self) -> str:
        """Stop and remove Gateway container, regardless of how it was started."""
        gateway_info = self._service_state.check_gateway()
        container_name = gateway_info.container_name
        if not container_name:
            return "Gateway is not running."

        stop = await asyncio.create_subprocess_exec(
            "docker",
            "stop",
            container_name,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        stop_out = await stop.communicate()
        if stop.returncode != 0:
            text = stop_out[0].decode(errors="replace").strip() if stop_out[0] else ""
            return f"Failed to stop Gateway ({container_name}, exit {stop.returncode}).\n{text}"

        rm = await asyncio.create_subprocess_exec(
            "docker",
            "rm",
            container_name,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        await rm.communicate()
        return f"Gateway stopped and removed ({container_name})."

    async def start_stargate(self) -> str:
        """Start Stargate as host process, detecting immediate crashes."""
        script = (
            self._root
            / "services"
            / "universal-stargate"
            / "scripts"
            / "start-stargate.sh"
        )
        if not script.exists():
            return f"Script not found: {script}"

        config_path = self._ensure_stargate_config()
        env = self._build_env()
        env["STARGATE_CONFIG"] = str(config_path)
        env["STARGATE_MODE"] = "master"

        log_path = Path("/tmp/logs/universal-stargate/tui-startup.log")
        log_path.parent.mkdir(parents=True, exist_ok=True)

        with log_path.open("w") as log_fh:
            process = await asyncio.create_subprocess_exec(
                str(script),
                "debug",
                env=env,
                cwd=str(self._root),
                stdout=log_fh,
                stderr=asyncio.subprocess.STDOUT,
                start_new_session=True,
            )

        try:
            exit_code = await asyncio.wait_for(process.wait(), timeout=3.0)
            tail = log_path.read_text(errors="replace")[-1500:]
            return f"Stargate failed (exit {exit_code}).\n{tail}"
        except TimeoutError:
            self._write_pid_file(process.pid)
            return f"Stargate starting (PID {process.pid})."

    async def stop_stargate(self) -> str:
        """Stop Stargate regardless of whether the PID file is current.

        Three cases handled in order:
        1. PID file present and alive → SIGTERM the recorded PID.
        2. PID file absent/stale but port open → locate listener via ss(8).
        3. Port closed → nothing to do.
        """
        pid_file = _GATEWAY_DIR / "stargate.pid"
        port = ServiceState.STARGATE_PORT
        port_open = self._service_state._port_open(port)

        recorded_pid: int | None = None
        if pid_file.exists():
            try:
                recorded_pid = int(pid_file.read_text().strip())
            except (ValueError, OSError) as e:
                logger.error("Corrupt PID file %s: %s", pid_file, e)
                pid_file.unlink(missing_ok=True)

        if recorded_pid is not None and self._service_state._pid_alive(recorded_pid):
            if not port_open:
                pid_file.unlink(missing_ok=True)
                return (
                    f"PID {recorded_pid} is alive but port {port} is closed — "
                    "not Stargate. Stale PID file removed."
                )
            return self._kill_stargate_pid(recorded_pid, pid_file)

        # PID dead or no valid file — clean up and try to find the real listener.
        pid_file.unlink(missing_ok=True)
        if not port_open:
            if recorded_pid is not None:
                return f"Stale PID file removed (PID {recorded_pid} already dead)."
            return "Stargate is not running."

        listener = self._service_state._find_listener_pid(port)
        if listener is None:
            return (
                f"Port {port} is open but the listener could not be identified.\n"
                "Run: ss -tlnp 'sport = :9999'"
            )
        return self._kill_stargate_pid(listener, None)

    def _kill_stargate_pid(self, pid: int, pid_file: Path | None) -> str:
        """Send SIGTERM to pid; remove pid_file if provided."""
        try:
            os.kill(pid, signal.SIGTERM)
            if pid_file is not None:
                pid_file.unlink(missing_ok=True)
            return f"Sent SIGTERM to Stargate (PID {pid})."
        except ProcessLookupError:
            if pid_file is not None:
                pid_file.unlink(missing_ok=True)
            return "Stargate already exited."
        except PermissionError as e:
            logger.error("Cannot kill Stargate PID %d: %s", pid, e)
            return f"Cannot stop Stargate (PID {pid}): {e}"

    @staticmethod
    def _write_pid_file(pid: int) -> None:
        _GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
        pid_path = _GATEWAY_DIR / "stargate.pid"
        pid_path.write_text(str(pid) + "\n")

    def _ensure_stargate_config(self) -> Path:
        """Return path to ~/.gateway/stargate.yaml, generating if absent or relay.

        Regenerates the master config if the existing file is a relay config
        (left behind by ``./manage relay``). Relay configs are auto-generated
        from template, so no user edits are lost.

        Also ensures sibling files that Stargate requires at startup
        (profiles.yaml, model_transformations.yaml) exist.
        """
        _GATEWAY_DIR.mkdir(parents=True, exist_ok=True)

        config_path = _GATEWAY_DIR / "stargate.yaml"
        if config_path.exists() and self._is_relay_config(config_path):
            logger.warning(
                "Existing %s is a relay config — regenerating master config",
                config_path,
            )
            config_path.unlink()
        if not config_path.exists():
            config_path.write_text(_STARGATE_CONFIG_TEMPLATE)
            logger.info("Generated stargate config: %s", config_path)

        for name, content in _GATEWAY_SEED_FILES.items():
            path = _GATEWAY_DIR / name
            if not path.exists():
                path.write_text(content)
                logger.info("Generated %s", path)

        return config_path

    def _ensure_node_env(self, node_id: str) -> Path:
        """Return path to ~/.gateway/nodes/<node_id>.env, generating if absent.

        Reads MODEL_PATH from .env.local (MODEL_PATH_ROOT) and generates
        a federation key for the edge container.
        """
        _NODES_DIR.mkdir(parents=True, exist_ok=True)
        node_env = _NODES_DIR / f"{node_id}.env"
        if node_env.exists():
            return node_env

        base_env = load_env_file(self._root / ".env.local")
        model_path = base_env.get("MODEL_PATH_ROOT", str(Path.home() / ".models"))
        federation_key = secrets.token_hex(24)

        lines = [
            f"NODE_ID={node_id}",
            f"MODEL_PATH={model_path}",
            f"FEDERATION_KEY_EDGE={federation_key}",
        ]
        node_env.write_text("\n".join(lines) + "\n")
        logger.info("Generated node env: %s", node_env)
        return node_env

    def _ensure_bind_mount_dirs(self, node_id: str, model_path: Path) -> str | None:
        """Pre-create bind mount source dirs so Docker doesn't create them as root.

        Docker daemon auto-creates missing bind mount sources owned by root:root.
        Creating them here (as the invoking user) prevents that.

        Returns an error message if any dir is root-owned, None on success.
        """
        dirs = [
            model_path,
            _GATEWAY_DIR / "catalog",
            _GATEWAY_DIR / "nodes",
            Path.home() / ".cache" / "vllm",
            self._root / "tmp" / "gpu-nodes" / node_id / "logs",
            self._root / "tmp" / "gpu-nodes" / node_id / "output",
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        root_owned = [d for d in dirs if d.exists() and d.stat().st_uid == 0]
        if root_owned and os.getuid() != 0:
            paths = "\n  ".join(str(d) for d in root_owned)
            uid, gid = os.getuid(), os.getgid()
            return (
                f"Bind mount dirs owned by root (Docker created them):\n"
                f"  {paths}\n"
                f"Fix with:\n  sudo chown -R {uid}:{gid} {' '.join(str(d) for d in root_owned)}"
            )
        return None

    def ensure_relay_dirs(self, node_id: str, model_path: Path) -> str | None:
        """Ensure socket dir and bind-mount dirs for relay. Return error message or None."""
        self._ensure_socket_dir()
        return self._ensure_bind_mount_dirs(node_id, model_path)

    @staticmethod
    def _is_relay_config(config_path: Path) -> bool:
        """Detect whether stargate.yaml was generated by the relay template."""
        try:
            text = config_path.read_text()
        except OSError:
            return False
        return "mode: remote" in text or "mode: relay" in text

    def _ensure_socket_dir(self) -> None:
        socket_dir = Path("/tmp/universal-protocol")
        socket_dir.mkdir(parents=True, exist_ok=True)
        try:
            socket_dir.chmod(0o777)
        except PermissionError:
            logger.warning("Cannot chmod %s", socket_dir)

    def _build_env(self, node_env_path: Path | None = None) -> dict[str, str]:
        """Build env dict from os.environ + .env.local + optional node env."""
        env = dict(os.environ)
        env.update(load_env_file(self._root / ".env.local"))
        if node_env_path:
            env.update(load_env_file(node_env_path))
        return env
