"""Service configuration — env files, config generation, bind mount setup."""

import logging
import os
import secrets
from pathlib import Path

logger = logging.getLogger(__name__)

GATEWAY_DIR = Path.home() / ".gateway"
NODES_DIR = GATEWAY_DIR / "nodes"

_STARGATE_CONFIG_TEMPLATE = """\
# TUI-managed Stargate configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# Architecture:
#   Client → Master Stargate:9999 (host) → Unix socket → Edge+Gateway (container)
#   Container: network_mode=none, fully network-isolated

proxy:
  port: 9999
  host: "0.0.0.0"
  cors_enabled: true

federation:
  mode: master
  stargate_id: "master-localhost"

  local_edge:
    socket_path: "/tmp/universal-protocol/edge-localhost.sock"
    stargate_id: "edge-localhost"
    api_key: "onboarding-dev-key"

  ping_interval_ms: 15000

  # remotes: []

logging:
  level: "INFO"
  enable_console: true
  enable_file: true
  log_dir: "/tmp/logs/universal-stargate"

model_routing:
  default_sticky: true

request_queue:
  max_size: 1000
  default_timeout: 300

pipelines:
  search_paths:
    - "pipelines"
    - "pipelines.local"
    - "~/.pipelines"
  hot_reload:
    enabled: true
    debounce_ms: 2000

debug_events:
  persistence:
    enabled: false
    directory: "/tmp/stargate-events"
    max_file_size_mb: 50
    max_files: 1
    flush_interval_seconds: 1.0

# Cloud proxy integration (optional).
# Requires the cloud proxy service to be running (start via ./manage).
# cloud_proxy:
#   url: "http://localhost:8200"
"""

# Fallback content when service config files are unavailable
_GATEWAY_SEED_FALLBACK: dict[str, str] = {
    "profiles.yaml": "profiles: {}\n",
    "model_transformations.yaml": "transformations: {}\n",
}

# ∀ file ∈ _GATEWAY_SEED_FALLBACK: if content == fallback, file was never populated
_SERVICE_CONFIG_DIR = Path(__file__).parents[4] / "services/universal-stargate/config"


def _gateway_seed_content(name: str) -> str:
    """Return seed content for a ~/.gateway config file.

    Reads from services/universal-stargate/config/ when available so that
    profiles and transformations ship with working defaults. Falls back to
    the empty-placeholder string if the source file is missing.
    """
    source = _SERVICE_CONFIG_DIR / name
    if source.exists():
        return source.read_text()
    fallback = _GATEWAY_SEED_FALLBACK.get(name, "")
    logger.warning("Service config not found: %s — using empty fallback", source)
    return fallback


def load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines from an env file. Shared for TUI and headless relay."""
    entries: dict[str, str] = {}
    if not path.exists():
        return entries
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            entries[key.strip()] = os.path.expandvars(value.strip())
    return entries


def build_service_env(
    workspace_root: Path, node_env_path: Path | None = None
) -> dict[str, str]:
    """Build env dict from os.environ + .env.local + optional node env."""
    env = dict(os.environ)
    env.update(load_env_file(workspace_root / ".env.local"))
    if node_env_path:
        env.update(load_env_file(node_env_path))
    return env


def ensure_stargate_config() -> Path:
    """Return path to ~/.gateway/stargate.yaml, generating if absent or relay.

    Regenerates the master config if the existing file is a relay config
    (left behind by ``./manage relay``). Relay configs are auto-generated
    from template, so no user edits are lost.

    Also ensures sibling files that Stargate requires at startup
    (profiles.yaml, model_transformations.yaml) exist.
    """
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)

    config_path = GATEWAY_DIR / "stargate.yaml"
    if config_path.exists() and is_relay_config(config_path):
        logger.warning(
            "Existing %s is a relay config — regenerating master config",
            config_path,
        )
        config_path.unlink()
    if not config_path.exists():
        config_path.write_text(_STARGATE_CONFIG_TEMPLATE)
        logger.info("Generated stargate config: %s", config_path)

    for name, fallback in _GATEWAY_SEED_FALLBACK.items():
        path = GATEWAY_DIR / name
        existing = path.read_text() if path.exists() else None
        if existing is None or existing == fallback:
            # Create or reseed: file absent OR previously seeded with empty placeholder
            content = _gateway_seed_content(name)
            path.write_text(content)
            action = "Reseeded" if existing == fallback else "Generated"
            logger.info("%s %s", action, path)

    return config_path


def ensure_node_env(workspace_root: Path, node_id: str) -> Path:
    """Return path to ~/.gateway/nodes/<node_id>.env, generating if absent.

    Seeds MODEL_PATH from .env.local (MODEL_PATH_ROOT) as a one-time
    migration for existing installs, then generates a federation key.
    """
    NODES_DIR.mkdir(parents=True, exist_ok=True)
    node_env = NODES_DIR / f"{node_id}.env"
    if node_env.exists():
        return node_env

    base_env = load_env_file(workspace_root / ".env.local")
    model_path = base_env.get("MODEL_PATH_ROOT", str(Path.home() / ".models"))
    federation_key = secrets.token_hex(24)

    lines = [
        f"NODE_ID={node_id}",
        f"MODEL_PATH={model_path}",
        f"FEDERATION_KEY_EDGE={federation_key}",
    ]
    node_env.write_text("\n".join(lines) + "\n")
    logger.info("Generated node env: %s", node_env)
    return node_env


def ensure_bind_mount_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Pre-create bind mount source dirs so Docker doesn't create them as root.

    Docker daemon auto-creates missing bind mount sources owned by root:root.
    Creating them here (as the invoking user) prevents that.

    Returns an error message if any dir is root-owned, None on success.
    """
    dirs = [
        model_path,
        GATEWAY_DIR / "catalog",
        GATEWAY_DIR / "nodes",
        Path.home() / ".cache" / "vllm",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "logs",
        workspace_root / "tmp" / "gpu-nodes" / node_id / "output",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    root_owned = [d for d in dirs if d.exists() and d.stat().st_uid == 0]
    if root_owned and os.getuid() != 0:
        paths = "\n  ".join(str(d) for d in root_owned)
        uid, gid = os.getuid(), os.getgid()
        return (
            f"Bind mount dirs owned by root (Docker created them):\n"
            f"  {paths}\n"
            f"Fix with:\n  sudo chown -R {uid}:{gid} {' '.join(str(d) for d in root_owned)}"
        )
    return None


def ensure_socket_dir() -> str | None:
    """Ensure /tmp/universal-protocol exists and is world-writable/traversable.

    Returns an error message if the directory cannot be made world-writable,
    None on success.  The container bind-mounts this directory and its appuser
    (a different uid than the host user) writes a Unix socket into it — so the
    directory must be world-writable, not just writable by the current host user.
    """
    import stat as stat_mod

    socket_dir = Path("/tmp/universal-protocol")
    socket_dir.mkdir(parents=True, exist_ok=True)
    try:
        socket_dir.chmod(0o777)
    except PermissionError:
        mode = stat_mod.S_IMODE(socket_dir.stat().st_mode)
        logger.warning(
            "Cannot chmod %s (current mode=%o, uid=%d)",
            socket_dir,
            mode,
            socket_dir.stat().st_uid,
        )
    mode = stat_mod.S_IMODE(socket_dir.stat().st_mode)
    world_writable = bool(mode & stat_mod.S_IWOTH)
    world_executable = bool(mode & stat_mod.S_IXOTH)
    if not (world_writable and world_executable):
        return (
            f"Socket directory {socket_dir} is not writable/traversable "
            f"(owned by uid={socket_dir.stat().st_uid}, mode={oct(mode)}). "
            f"Fix with: sudo chmod 777 {socket_dir}"
        )
    return None


def ensure_relay_dirs(
    workspace_root: Path, node_id: str, model_path: Path
) -> str | None:
    """Ensure socket dir and bind-mount dirs for relay. Return error message or None."""
    err = ensure_socket_dir()
    if err:
        return err
    return ensure_bind_mount_dirs(workspace_root, node_id, model_path)


_CLOUD_PROXY_CONFIG_TEMPLATE = """\
# Cloud Proxy configuration
# Generated by ./manage — edit freely, will not be overwritten.
#
# The cloud proxy is a separate service that holds API keys and
# forwards requests to cloud providers. Stargate connects to it
# over loopback — no API keys in Stargate config.
#
# Uncomment and configure a provider to enable cloud models:

port: 8200

# Bind address. Default is loopback-only (127.0.0.1).
# Set to a LAN interface IP (e.g. 192.168.1.x) or 0.0.0.0 to expose on the
# local subnet. The cloud proxy holds API keys — do not expose to the internet.
# host: "127.0.0.1"

# providers:
#   - provider: openrouter
#     api_key_env: OPENROUTER_API_KEY
#     base_url: https://openrouter.ai/api/v1
#     max_concurrent: 20
#     refresh_interval_hours: 6
#     allow_prefixes:
#       - "anthropic/"
#       - "openai/"
#       - "google/"
"""


def ensure_cloud_proxy_config() -> Path:
    """Return path to ~/.gateway/cloud-proxy.yaml, generating if absent."""
    GATEWAY_DIR.mkdir(parents=True, exist_ok=True)
    config_path = GATEWAY_DIR / "cloud-proxy.yaml"
    if not config_path.exists():
        config_path.write_text(_CLOUD_PROXY_CONFIG_TEMPLATE)
        logger.info("Generated cloud proxy config: %s", config_path)
    return config_path


def read_cloud_proxy_port(config_path: Path | None = None) -> int:
    """Read the port from cloud-proxy.yaml, defaulting to 8200.

    Tolerant: returns 8200 if the file is missing, unparseable, or the
    port field is absent/invalid.
    """
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_port = 8200
    try:
        from services.universal_cloud_proxy.config import DEFAULT_PORT, load_config

        default_port = DEFAULT_PORT
        return load_config(path).port
    except Exception:
        logger.warning("Could not read port from %s — using default 8200", path)
    return default_port


def read_cloud_proxy_host(config_path: Path | None = None) -> str:
    """Read the host from cloud-proxy.yaml, defaulting to 127.0.0.1.

    Tolerant: returns 127.0.0.1 if the file is missing, unparseable, or the
    host field is absent/invalid.
    """
    path = config_path or (GATEWAY_DIR / "cloud-proxy.yaml")
    default_host = "127.0.0.1"
    try:
        from services.universal_cloud_proxy.config import DEFAULT_HOST, load_config

        default_host = DEFAULT_HOST
        return load_config(path).host
    except Exception:
        logger.warning("Could not read host from %s — using default 127.0.0.1", path)
    return default_host


def is_relay_config(config_path: Path) -> bool:
    """Detect whether stargate.yaml was generated by the relay template."""
    try:
        text = config_path.read_text()
    except OSError:
        return False
    return "mode: remote" in text or "mode: relay" in text
