"""Dogfood / mechanical fixture package — not production API."""

from foo.briefing_fixture import (
    ADMIT_SUBJECT_PREFIX,
    ADMIT_SUBJECT_PRIOR,
    BASE_ADMIT_BODY,
    BRIEFING_FORBIDDEN_SUBSTRINGS,
    BRIEFING_HEADER,
    BRIEFING_REQUIRED_SUBSTRINGS,
    CODE_WORK_CONTRACTS,
    FROM_AUTO,
    MAX_BRIEFING_LINES,
    MINI_BRIEFING_SAMPLE,
    TURNS_FIRST_EPISODE,
    TURNS_FOLLOW_ON,
    TURNS_NO_PRIOR_ADMITS,
    TURNS_PRIOR_ADMIT,
)

__all__ = [
    "ADMIT_SUBJECT_PREFIX",
    "ADMIT_SUBJECT_PRIOR",
    "BASE_ADMIT_BODY",
    "BRIEFING_FORBIDDEN_SUBSTRINGS",
    "BRIEFING_HEADER",
    "BRIEFING_REQUIRED_SUBSTRINGS",
    "CODE_WORK_CONTRACTS",
    "FROM_AUTO",
    "MAX_BRIEFING_LINES",
    "MINI_BRIEFING_SAMPLE",
    "TURNS_FIRST_EPISODE",
    "TURNS_FOLLOW_ON",
    "TURNS_NO_PRIOR_ADMITS",
    "TURNS_PRIOR_ADMIT",
]
