"""Target-specific renderer + AGENTS.md splicer for gen_rules.

Cursor target → `.cursor/rules/*.mdc` body (with YAML front matter and DO NOT EDIT
header before it). grok-direct target → AGENTS.md splice content (with +1 heading
offset for source-derived content; table-variants are emitted verbatim).
"""

from __future__ import annotations

import re
from pathlib import Path

from .parser import ParsedSource

_CURSOR = "cursor"
_GROK = "grok-direct"

_DO_NOT_EDIT_TEMPLATE = (
    "<!-- DO NOT EDIT — generated by scripts/gen-rules from {source}. "
    "Run `scripts/gen-rules --check` to verify drift. -->"
)

_HEADING_RE = re.compile(r"^(#{1,5})(\s+\S)", re.MULTILINE)


def _do_not_edit(source_rel: str) -> str:
    return _DO_NOT_EDIT_TEMPLATE.format(source=source_rel)


def _shift_headings(text: str, offset: int) -> str:
    if offset == 0:
        return text

    def repl(m: re.Match[str]) -> str:
        hashes = m.group(1)
        new_depth = min(len(hashes) + offset, 6)
        return "#" * new_depth + m.group(2)

    return _HEADING_RE.sub(repl, text)


def _join_blocks(parsed: ParsedSource, target: str) -> str:
    pieces = [b.content for b in parsed.blocks_for(target)]
    return "".join(pieces)


def render_cursor_mdc(parsed: ParsedSource, source_rel: str) -> str:
    """Render the .cursor/rules/*.mdc output for a source file."""
    body = _join_blocks(parsed, _CURSOR)
    parts: list[str] = [_do_not_edit(source_rel) + "\n"]
    if parsed.frontmatter_cursor is not None:
        parts.append("---\n")
        parts.append(parsed.frontmatter_cursor)
        if not parsed.frontmatter_cursor.endswith("\n"):
            parts.append("\n")
        parts.append("---\n")
    parts.append("\n")
    parts.append(body)
    out = "".join(parts)
    if not out.endswith("\n"):
        out += "\n"
    return out


def render_agents_md_section(
    parsed: ParsedSource,
    source_rel: str,
    *,
    heading_offset: int = 1,
) -> str:
    """Render the AGENTS.md splice body (between gen-rules:start/end markers)."""
    body = _join_blocks(parsed, _GROK)
    body = _shift_headings(body, heading_offset)
    out = _do_not_edit(source_rel) + "\n" + body
    if not out.endswith("\n"):
        out += "\n"
    return out


def render_table_variant(table_md: str, source_rel: str) -> str:
    """Render a pre-normalized table-variant file for AGENTS.md splice (no offset)."""
    out = _do_not_edit(source_rel) + "\n" + table_md
    if not out.endswith("\n"):
        out += "\n"
    return out


def splice_agents_md(agents_md_path: Path, section_id: str, body: str) -> str:
    """Return the AGENTS.md text with `body` spliced between section markers.

    Raises if the marker pair for `section_id` is not present.
    """
    text = agents_md_path.read_text()
    start = f"<!-- gen-rules:start:{section_id} -->"
    end = f"<!-- gen-rules:end:{section_id} -->"
    s_idx = text.find(start)
    e_idx = text.find(end)
    if s_idx == -1 or e_idx == -1 or e_idx < s_idx:
        raise ValueError(
            f"ERROR: gen-rules markers for section {section_id!r} not found in {agents_md_path}. "
            "Install marker pair before running gen-rules write/check."
        )
    before = text[: s_idx + len(start)]
    after = text[e_idx:]
    if not body.endswith("\n"):
        body += "\n"
    return before + "\n" + body + after


def extract_agents_md_section(agents_md_path: Path, section_id: str) -> str | None:
    """Extract current body between gen-rules markers (None if markers absent)."""
    text = agents_md_path.read_text()
    start = f"<!-- gen-rules:start:{section_id} -->"
    end = f"<!-- gen-rules:end:{section_id} -->"
    s_idx = text.find(start)
    e_idx = text.find(end)
    if s_idx == -1 or e_idx == -1 or e_idx < s_idx:
        return None
    body = text[s_idx + len(start) : e_idx]
    return body.lstrip("\n")
