"""Target-specific renderer for gen_rules.

Cursor target → `.cursor/rules/*.mdc` body (with YAML front matter and DO NOT EDIT
header before it).
"""

from __future__ import annotations

from .parser import ParsedSource

_CURSOR = "cursor"

_DO_NOT_EDIT_TEMPLATE = (
    "<!-- DO NOT EDIT — generated by scripts/gen-rules from {source}. "
    "Run `scripts/gen-rules --check` to verify drift. -->"
)


def _do_not_edit(source_rel: str) -> str:
    return _DO_NOT_EDIT_TEMPLATE.format(source=source_rel)


def _join_blocks(parsed: ParsedSource, target: str) -> str:
    pieces = [b.content for b in parsed.blocks_for(target)]
    return "".join(pieces)


def render_cursor_mdc(parsed: ParsedSource, source_rel: str) -> str:
    """Render the .cursor/rules/*.mdc output for a source file."""
    body = _join_blocks(parsed, _CURSOR)
    parts: list[str] = [_do_not_edit(source_rel) + "\n"]
    if parsed.frontmatter_cursor is not None:
        parts.append("---\n")
        parts.append(parsed.frontmatter_cursor)
        if not parsed.frontmatter_cursor.endswith("\n"):
            parts.append("\n")
        parts.append("---\n")
    parts.append("\n")
    parts.append(body)
    out = "".join(parts)
    if not out.endswith("\n"):
        out += "\n"
    return out
