"""Request/response models for the RAG service API (barrel re-export).

Implementation is split across sibling modules to satisfy SLOC limits; callers
should continue to use ``from services.rag.models import ...``.
"""

from __future__ import annotations

from .articles_ops import (
    ArticleListingItem,
    ArticleListingResponse,
    ArticleUpsertRequest,
    ArticleUpsertResponse,
    CoverageResponse,
    EmbedBatchRequest,
    EmbedBatchResponse,
    PipelineStage,
    PrefixCoverage,
    RefreshCorpusHintsRequest,
    RefreshCorpusHintsResponse,
    RerankRequest,
    RerankResponse,
    ScopeCoverage,
    ScopeRegisterRequest,
    ScopeRegisterResponse,
    SourceStatusItem,
    SourceStatusResponse,
)
from .extraction_admin import (
    ChunkByIndexItem,
    ChunkIndexGroup,
    ChunksByIndexRequest,
    ChunksByIndexResponse,
    ClearDirectoryRequest,
    ClearDirectoryResponse,
    DirectoryDeleteResponse,
    ExtractionExportItem,
    ExtractionExportResponse,
    ExtractionQueueBreakdownModel,
    ExtractionQueueResponse,
    ExtractionQueueRowModel,
    FailedChunkItem,
    FailedExtractionResponse,
    SourceDeleteResponse,
)
from .search_index import (
    RECENCY_DECAY_LAMBDA,
    ClearResponse,
    DeleteIndexingFailureResponse,
    DeleteResult,
    IndexDirectoryRequest,
    IndexDirectoryResponse,
    IndexingFailureResponse,
    IndexingFailuresListResponse,
    IndexingStatusResponse,
    IndexRequest,
    IndexResult,
    RetryIndexingFailureResponse,
    ScopeInfo,
    ScopesResponse,
    SearchRequest,
    SearchResponse,
    SourceResponse,
    SourcesResponse,
    StatsResponse,
    WatcherStatusItem,
)

__all__ = [
    "RECENCY_DECAY_LAMBDA",
    "ArticleListingItem",
    "ArticleListingResponse",
    "ArticleUpsertRequest",
    "ArticleUpsertResponse",
    "ChunkByIndexItem",
    "ChunkIndexGroup",
    "ChunksByIndexRequest",
    "ChunksByIndexResponse",
    "ClearDirectoryRequest",
    "ClearDirectoryResponse",
    "ClearResponse",
    "CoverageResponse",
    "DeleteIndexingFailureResponse",
    "DeleteResult",
    "DirectoryDeleteResponse",
    "EmbedBatchRequest",
    "EmbedBatchResponse",
    "ExtractionExportItem",
    "ExtractionExportResponse",
    "ExtractionQueueBreakdownModel",
    "ExtractionQueueResponse",
    "ExtractionQueueRowModel",
    "FailedChunkItem",
    "FailedExtractionResponse",
    "IndexDirectoryRequest",
    "IndexDirectoryResponse",
    "IndexRequest",
    "IndexResult",
    "IndexingFailureResponse",
    "IndexingFailuresListResponse",
    "IndexingStatusResponse",
    "PipelineStage",
    "PrefixCoverage",
    "RefreshCorpusHintsRequest",
    "RefreshCorpusHintsResponse",
    "RerankRequest",
    "RerankResponse",
    "RetryIndexingFailureResponse",
    "ScopeCoverage",
    "ScopeInfo",
    "ScopeRegisterRequest",
    "ScopeRegisterResponse",
    "ScopesResponse",
    "SearchRequest",
    "SearchResponse",
    "SourceDeleteResponse",
    "SourceResponse",
    "SourceStatusItem",
    "SourceStatusResponse",
    "SourcesResponse",
    "StatsResponse",
    "WatcherStatusItem",
]
